// server/legal-content/uz/civilCode.js
// ============================================================================
// O'ZBEKISTON RESPUBLIKASINING FUQAROLIK KODEKSI — 1-QISM (1–385 moddalar)
//
// Manba: lex.uz (https://lex.uz/docs/-111189)
// So'nggi tekshirilgan: 2026-yil 30-iyun (PDF nusxasi asosida)
//
// OYLIK TEKSHIRUV TARTIBI:
//   1. lex.uz/docs/-111189 sahifasini oching
//   2. "Oldingi tahrirga qarang" yozuvlari bilan belgilangan moddalari
//      o'zgargan bo'lishi mumkin — ularni avval tekshiring
//   3. O'zgargan modda matni va nomini bu faylda yangilang
//   4. Fayl tepasidagi "So'nggi tekshirilgan" sanasini o'zgartiring
//
// TUZILISH: bo'lim → kichik bo'lim → bob → modda
// Har bir modda: { no, title } — matn jonli (lex.uz dan real vaqtda) olinadi
// ============================================================================

const CIVIL_CODE_TOC = {
  key: 'civil',
  name: "Fuqarolik kodeksi (1-qism)",
  officialName: "O'zbekiston Respublikasining Fuqarolik kodeksi",
  url: 'https://lex.uz/docs/-111189',
  adoptedDate: '1995-12-21',
  effectiveDate: '1997-03-01',
  lastChecked: '2026-06-30',
  detailedToc: true,
  tocSections: [
    // ========================================================
    // I BO'LIM — UMUMIY QOIDALAR
    // ========================================================
    {
      title: "I BO'LIM. UMUMIY QOIDALAR",
      subsections: [
        {
          title: "1-Kichik bo'lim. ASOSIY QOIDALAR",
          chapters: [
            {
              title: "1-BOB. FUQAROLIK QONUNCHILIGI",
              articles: [
                { no: 1, title: "Fuqarolik qonunchiligining asosiy negizlari" },
                { no: 2, title: "Fuqarolik qonunchiligi bilan tartibga solinadigan munosabatlar" },
                { no: 3, title: "Fuqarolik qonunchiligi hujjatlari" },
                { no: 4, title: "Fuqarolik qonunchiligining vaqt bo'yicha amal qilishi" },
                { no: 5, title: "Fuqarolik qonunchiligini o'xshashlik bo'yicha qo'llash" },
                { no: 6, title: "Ish muomalasi odatlari. Mahalliy odat va an'analar" },
                { no: 7, title: "Fuqarolik qonunchiligi va xalqaro shartnomalar hamda bitimlar" },
              ],
            },
            {
              title: "2-BOB. FUQAROLIK HUQUQ VA BURCHLARINING VUJUDGA KELISHI. FUQAROLIK HUQUQLARINI AMALGA OSHIRISH VA HIMOYA QILISH",
              articles: [
                { no: 8, title: "Fuqarolik huquq va burchlarining vujudga kelish asoslari" },
                { no: 9, title: "Fuqarolik huquqlarini amalga oshirish" },
                { no: 10, title: "Fuqarolik huquqlarini sud orqali himoya qilish" },
                { no: 11, title: "Fuqarolik huquqlarini himoya qilish usullari" },
                { no: 12, title: "Davlat organining yoki fuqarolarning o'zini o'zi boshqarish organining hujjatini haqiqiy emas deb topish" },
                { no: 13, title: "Fuqarolik huquqlarini shaxsning o'zi himoya qilishi" },
                { no: 14, title: "Zararni qoplash" },
                { no: 15, title: "Davlat organlari va fuqarolarning o'zini o'zi boshqarish organlari tomonidan yetkazilgan zararni to'lash" },
              ],
            },
          ],
        },
        {
          title: "2-Kichik bo'lim. SHAXSLAR",
          chapters: [
            {
              title: "3-BOB. FUQAROLAR (JISMONIY SHAXSLAR)",
              articles: [
                { no: 16, title: "Fuqaro (jismoniy shaxs) tushunchasi" },
                { no: 17, title: "Fuqarolarning huquq layoqati" },
                { no: 18, title: "Fuqarolar huquq layoqatining mazmuni" },
                { no: 19, title: "Fuqaroning ismi" },
                { no: 20, title: "Ismni himoya qilish" },
                { no: 21, title: "Fuqaroning yashash joyi" },
                { no: 22, title: "Fuqaroning muomala layoqati" },
                { no: 23, title: "Fuqaroning huquq layoqati va muomala layoqatini cheklashga yo'l qo'yilmasligi" },
                { no: 24, title: "Fuqaroning tadbirkorlik faoliyati" },
                { no: 25, title: "Fuqaroning mulkiy javobgarligi" },
                { no: 26, title: "Yakka tartibdagi tadbirkorning va yakka tartibdagi tadbirkor maqomini yo'qotgan jismoniy shaxsning to'lovga qobiliyatsizligi" },
                { no: '26¹', title: "Jismoniy shaxsning to'lovga qobiliyatsizligi" },
                { no: 27, title: "O'n to'rt yoshdan o'n sakkiz yoshgacha bo'lgan voyaga yetmaganlarning muomala layoqati" },
                { no: 28, title: "Emansipatsiya" },
                { no: 29, title: "O'n to'rt yoshga to'lmagan voyaga yetmaganlarning muomala layoqati" },
                { no: 30, title: "Fuqaroni muomalaga layoqatsiz deb topish" },
                { no: 31, title: "Fuqaroning muomala layoqatini cheklash" },
                { no: 32, title: "Vasiylik va homiylik" },
                { no: 33, title: "Fuqaroni bedarak yo'qolgan deb topish" },
                { no: 34, title: "Fuqaroni bedarak yo'qolgan deb topish oqibatlari" },
                { no: 35, title: "Fuqaroni bedarak yo'qolgan deb topish haqidagi qarorning bekor qilinishi" },
                { no: 36, title: "Fuqaroni vafot etgan deb e'lon qilish" },
                { no: 37, title: "Vafot etgan deb e'lon qilingan fuqaro qaytib kelishining oqibatlari" },
                { no: 38, title: "Fuqarolik holati hujjatlarini qayd etish" },
              ],
            },
            {
              title: "4-BOB. YURIDIK SHAXSLAR",
              subchapters: [
                {
                  title: "1-§. Umumiy qoidalar",
                  articles: [
                    { no: 39, title: "Yuridik shaxs tushunchasi" },
                    { no: 40, title: "Yuridik shaxslarning turlari" },
                    { no: 41, title: "Yuridik shaxsning huquq layoqati" },
                    { no: 42, title: "Yuridik shaxslarning vujudga kelishi" },
                    { no: 43, title: "Yuridik shaxsning ta'sis hujjatlari" },
                    { no: 44, title: "Yuridik shaxslarni davlat ro'yxatidan o'tkazish" },
                    { no: 45, title: "Yuridik shaxsning organlari" },
                    { no: 46, title: "Yuridik shaxsning nomi va joylashgan yeri" },
                    { no: 47, title: "Vakolatxonalar va filiallar" },
                    { no: 48, title: "Yuridik shaxsning javobgarligi" },
                    { no: 49, title: "Yuridik shaxsni qayta tashkil etish" },
                    { no: 50, title: "Yuridik shaxslarni qayta tashkil etishda huquqiy vorislik" },
                    { no: 51, title: "Topshirish hujjati va taqsimlash balansi" },
                    { no: 52, title: "Yuridik shaxs qayta tashkil etilganida kreditorlar huquqlarining kafolatlari" },
                    { no: 53, title: "Yuridik shaxsni tugatish" },
                    { no: 54, title: "Yuridik shaxsni tugatish to'g'risida qaror qabul qilgan shaxsning burchlari" },
                    { no: 55, title: "Yuridik shaxsni tugatish tartibi" },
                    { no: 56, title: "Kreditorlarning talablarini qanoatlantirish" },
                    { no: 57, title: "Yuridik shaxsning to'lovga qobiliyatsizligi" },
                  ],
                },
                {
                  title: "2-§. Tijorat tashkilotlari",
                  articles: [
                    { no: 58, title: "Xo'jalik shirkatlari va jamiyatlari to'g'risidagi asosiy qoidalar" },
                    { no: 59, title: "Xo'jalik shirkati yoki jamiyati ishtirokchilarining huquq va burchlari" },
                    { no: 60, title: "To'liq shirkat" },
                    { no: 61, title: "Kommandit shirkat" },
                    { no: 62, title: "Mas'uliyati cheklangan jamiyat" },
                    { no: 63, title: "[O'z kuchini yo'qotgan — OʻRQ-1025, 2025-yil 8-may]" },
                    { no: 64, title: "Aksiyadorlik jamiyati" },
                    { no: 65, title: "[O'z kuchini yo'qotgan — OʻRQ-372, 2014]" },
                    { no: 66, title: "[O'z kuchini yo'qotgan — OʻRQ-372, 2014]" },
                    { no: 67, title: "Shu'ba xo'jalik jamiyati" },
                    { no: 68, title: "Qaram xo'jalik jamiyati" },
                    { no: 69, title: "Ishlab chiqarish kooperativlari" },
                    { no: 70, title: "[O'z kuchini yo'qotgan — OʻRQ-1025, 2025-yil 8-may]" },
                    { no: 71, title: "[O'z kuchini yo'qotgan — OʻRQ-1025, 2025-yil 8-may]" },
                    { no: 72, title: "[O'z kuchini yo'qotgan — OʻRQ-1025, 2025-yil 8-may]" },
                  ],
                },
                {
                  title: "3-§. Tijoratchi bo'lmagan tashkilotlar",
                  articles: [
                    { no: 73, title: "Matlubot kooperativi" },
                    { no: 74, title: "Jamoat birlashmalari" },
                    { no: 75, title: "Jamoat fondlari" },
                    { no: 76, title: "Muassasalar" },
                    { no: 77, title: "Yuridik shaxslar birlashmalari" },
                    { no: 78, title: "Fuqarolarning o'zini o'zi boshqarish organlari" },
                  ],
                },
              ],
            },
            {
              title: "5-BOB. DAVLAT FUQAROLIK-HUQUQIY MUNOSABATLAR ISHTIROKCHISI SIFATIDA",
              articles: [
                { no: 79, title: "Davlatning fuqarolik-huquqiy munosabatlarda ishtirok etishi" },
                { no: 80, title: "Davlat va yuridik shaxslar javobgarligining farqlab qo'yilishi" },
              ],
            },
          ],
        },
        {
          title: "3-Kichik bo'lim. OBYEKTLAR",
          chapters: [
            {
              title: "6-BOB. UMUMIY QOIDALAR",
              articles: [
                { no: 81, title: "Fuqarolik huquqlari obyektlarining turlari" },
                { no: 82, title: "Fuqarolik huquqlari obyektlarining muomalada bo'lishi" },
              ],
            },
            {
              title: "7-BOB. MODDIY NE'MATLAR",
              articles: [
                { no: 83, title: "Mol-mulkning turlari" },
                { no: 84, title: "Ko'chmas mol-mulkni davlat ro'yxatidan o'tkazish" },
                { no: 85, title: "Korxona" },
                { no: 86, title: "Ashyolarning tasnifi" },
                { no: 87, title: "Xususiy va turga xos alomatlari bilan belgilanadigan ashyolar" },
                { no: 88, title: "Bo'linadigan va bo'linmaydigan ashyolar" },
                { no: 89, title: "Iste'mol qilinadigan va iste'mol qilinmaydigan ashyolar" },
                { no: 90, title: "Asosiy va mansub ashyolar" },
                { no: 91, title: "Murakkab ashyolar" },
                { no: 92, title: "Hosil va daromadlarga bo'lgan huquq" },
                { no: 93, title: "Hayvonlar" },
                { no: 94, title: "Pul (valyuta)" },
                { no: 95, title: "Valyuta qimmatliklari" },
                { no: 96, title: "Qimmatli qog'ozlar" },
              ],
            },
            {
              title: "8-BOB. NOMODDIY NE'MATLAR",
              articles: [
                { no: 97, title: "Intellektual faoliyat natijalari" },
                { no: 98, title: "Xizmat va tijorat siri" },
                { no: 99, title: "Shaxsiy nomulkiy huquqlar va boshqa nomoddiy ne'matlar" },
                { no: 100, title: "Sha'n, qadr-qimmat va ishchanlik obro'sini himoya qilish" },
              ],
            },
          ],
        },
        {
          title: "4-Kichik bo'lim. BITIMLAR VA VAKILLIK",
          chapters: [
            {
              title: "9-BOB. BITIMLAR",
              subchapters: [
                {
                  title: "1-§. Bitimlar tushunchasi. Turlari va shakli",
                  articles: [
                    { no: 101, title: "Bitimlar tushunchasi" },
                    { no: 102, title: "Bitim turlari" },
                    { no: 103, title: "Bir taraflama bitimlarni huquqiy tartibga solish" },
                    { no: 104, title: "Shartli bitimlar" },
                    { no: 105, title: "Bitimlarning shakli" },
                    { no: 106, title: "Bitimning og'zaki shakli" },
                    { no: 107, title: "Bitimning yozma shakli" },
                    { no: 108, title: "Bitimning oddiy yozma shakli" },
                    { no: 109, title: "Bitimning oddiy yozma shakliga rioya qilmaslik oqibatlari" },
                    { no: 110, title: "Bitimlarni notarial tasdiqlash" },
                    { no: 111, title: "Bitimlarni davlat ro'yxatidan o'tkazish" },
                    { no: 112, title: "Bitimning notarial shakliga va uni ro'yxatdan o'tkazish talabiga rioya qilmaslikning oqibatlari" },
                  ],
                },
                {
                  title: "2-§. Bitimlarning haqiqiy emasligi",
                  articles: [
                    { no: 113, title: "Nizoli va o'z-o'zidan haqiqiy bo'lmagan bitimlar" },
                    { no: 114, title: "Bitimlar haqiqiy emasligining oqibatlari to'g'risidagi umumiy qoidalar" },
                    { no: 115, title: "Bitimning qonun talab qiladigan shakliga rioya etmaslik" },
                    { no: 116, title: "Qonunchilikning talablariga muvofiq bo'lmagan bitimning haqiqiy emasligi" },
                    { no: 117, title: "O'n to'rt yoshga to'lmagan shaxs tomonidan tuzilgan bitimning haqiqiy emasligi" },
                    { no: 118, title: "O'n to'rt yoshdan o'n sakkiz yoshgacha bo'lgan voyaga yetmagan shaxs tomonidan tuzilgan bitimning haqiqiy emasligi" },
                    { no: 119, title: "Muomalaga layoqatsiz deb topilgan fuqaro tomonidan tuzilgan bitimning haqiqiy emasligi" },
                    { no: 120, title: "Muomala layoqati cheklangan fuqaro tomonidan tuzilgan bitimning haqiqiy emasligi" },
                    { no: 121, title: "O'z harakatlarining ahamiyatini tushuna olmaydigan yoki ularni boshqara olmaydigan fuqaro tomonidan tuzilgan bitimning haqiqiy emasligi" },
                    { no: 122, title: "Yanglishish ta'sirida tuzilgan bitimning haqiqiy emasligi" },
                    { no: 123, title: "Aldash, zo'rlik, qo'rqitish, bir taraf vakilining ikkinchi taraf bilan yomon niyatda kelishishi yoki og'ir holatlar ta'sirida tuzilgan bitimning haqiqiy emasligi" },
                    { no: 124, title: "Qalbaki va ko'zbo'yamachilik uchun tuzilgan bitimning haqiqiy emasligi" },
                    { no: 125, title: "Yuridik shaxs huquqiy layoqatidan tashqariga chiqadigan bitimning haqiqiy emasligi" },
                    { no: 126, title: "Bitim tuzish vakolatlarini cheklash oqibatlari" },
                    { no: 127, title: "Bitimning haqiqiy emas deb hisoblanish payti" },
                    { no: 128, title: "Bitimning bir qismi haqiqiy emasligining oqibatlari" },
                  ],
                },
              ],
            },
            {
              title: "10-BOB. VAKILLIK VA ISHONCHNOMA",
              articles: [
                { no: 129, title: "Vakillik" },
                { no: 130, title: "Muomalaga layoqatli shaxslar nomidan vakillik qilish" },
                { no: 131, title: "Muomalaga layoqatsiz shaxslar nomidan vakillik qilish" },
                { no: 132, title: "Vakolatsiz vakillik" },
                { no: 133, title: "Tijorat vakilligi" },
                { no: 134, title: "Ishonchnoma" },
                { no: 135, title: "Ishonchnomaning shakli" },
                { no: 136, title: "Notarial tasdiqlangan ishonchnomalarga tenglashtirilgan ishonchnomalar" },
                { no: 137, title: "Ishonchnomaning boshqa shakllari" },
                { no: 138, title: "Yuridik shaxsning ishonchnomasi" },
                { no: 139, title: "Ishonchnomaning muddati" },
                { no: 140, title: "Ishonchnoma bo'yicha vakolatlarni boshqa shaxsga berish (boshqa shaxsga o'tkazish)" },
                { no: 141, title: "Ishonchnomaning bekor bo'lishi" },
                { no: 142, title: "Ishonchnomaning bekor bo'lganligi haqida shaxslarga xabar berish" },
                { no: 143, title: "Ishonchnoma olgan shaxsning ishonchnoma bekor bo'lganidan keyin qilgan harakatlari" },
                { no: 144, title: "Ishonchnomani qaytarish majburiyati" },
              ],
            },
          ],
        },
        {
          title: "5-Kichik bo'lim. MUDDATLAR. DA'VO MUDDATI",
          chapters: [
            {
              title: "11-BOB. MUDDATLARNI HISOBLASH",
              articles: [
                { no: 145, title: "Muddat belgilash" },
                { no: 146, title: "Vaqt davri bilan belgilangan muddatning boshlanishi" },
                { no: 147, title: "Vaqt davri bilan belgilangan muddatning tamom bo'lishi" },
                { no: 148, title: "Muddatning oxirgi kunida harakatni amalga oshirish tartibi" },
              ],
            },
            {
              title: "12-BOB. DA'VO MUDDATI",
              articles: [
                { no: 149, title: "Da'vo muddati tushunchasi" },
                { no: 150, title: "Umumiy da'vo muddati" },
                { no: 151, title: "Maxsus da'vo muddatlari" },
                { no: 152, title: "Da'vo muddatlarini o'zgartirish to'g'risidagi bitimning haqiqiy sanalmasligi" },
                { no: 153, title: "Da'vo muddatini qo'llash" },
                { no: 154, title: "Da'vo muddatining o'ta boshlanishi" },
                { no: 155, title: "Majburiyatdagi shaxslar almashinganida da'vo muddati" },
                { no: 156, title: "Da'vo muddati o'tishining to'xtatilishi" },
                { no: 157, title: "Da'vo muddati o'tishining uzilishi" },
                { no: 158, title: "Da'vo ko'rilmasdan qoldirilgan taqdirda da'vo muddatining o'tishi" },
                { no: 159, title: "Da'vo muddatini tiklash" },
                { no: 160, title: "Maxsus da'vo muddatining to'xtatilishi, uzilishi va tiklanishi" },
                { no: 161, title: "Da'vo muddati o'tganidan keyin majburiyatni bajarish" },
                { no: 162, title: "Qo'shimcha talablarga nisbatan da'vo muddatini qo'llash" },
                { no: 163, title: "Da'vo muddati joriy qilinmaydigan talablar" },
              ],
            },
          ],
        },
      ],
    },

    // ========================================================
    // II BO'LIM — MULK HUQUQI VA BOSHQA ASHYOVIY HUQUQLAR
    // ========================================================
    {
      title: "II BO'LIM. MULK HUQUQI VA BOSHQA ASHYOVIY HUQUQLAR",
      chapters: [
        {
          title: "13-BOB. UMUMIY QOIDALAR",
          articles: [
            { no: 164, title: "Mulk huquqi tushunchasi" },
            { no: 165, title: "Mulkdor bo'lmagan shaxslarning ashyoviy huquqlarining mazmuni" },
            { no: 166, title: "Mulkning daxlsizligi" },
            { no: 167, title: "Mulk shakllari" },
            { no: 168, title: "Mulk huquqining subyektlari" },
            { no: 169, title: "Mulk huquqining obyektlari" },
            { no: 170, title: "Yerga va boshqa tabiiy resurslarga bo'lgan mulk huquqi va o'zga ashyoviy huquqlar" },
            { no: 171, title: "Uy-joyga bo'lgan mulk huquqi va boshqa ashyoviy huquqlarni amalga oshirish xususiyatlari" },
            { no: 172, title: "Mulk huquqini amalga oshirish shartlari" },
            { no: 173, title: "O'zganing yer uchastkasidan cheklangan tarzda foydalanish (servitut) huquqi" },
            { no: '173¹', title: "Yer uchastkasiga bo'lgan huquq boshqa shaxsga o'tkazilganda servitutning saqlanishi" },
            { no: '173²', title: "Servitut shartlari" },
            { no: '173³', title: "Servitut uchun haq to'lash" },
            { no: '173⁴', title: "Servitut belgilangan yer uchastkasida muhandislik-kommunikatsiya tarmoqlari obyektlarini saqlash" },
            { no: '173⁵', title: "Servitut belgilangan yer uchastkasini bo'lish" },
            { no: '173⁶', title: "Servitutni o'zgartirish va bekor qilish" },
            { no: '173⁷', title: "Binolar, inshootlar va boshqa ko'chmas mulkka servitut belgilash" },
            { no: 174, title: "Mol-mulkni saqlash vazifasi" },
            { no: 175, title: "Mol-mulkning tasodifan nobud bo'lish yoki buzilish xavfi" },
          ],
        },
        {
          title: "14-BOB. OPERATIV BOSHQARISH HUQUQI",
          articles: [
            { no: 176, title: "[O'z kuchini yo'qotgan — OʻRQ-1025, 2025-yil 8-may]" },
            { no: 177, title: "[O'z kuchini yo'qotgan — OʻRQ-1025, 2025-yil 8-may]" },
            { no: 178, title: "Operativ boshqarish huquqi" },
            { no: 179, title: "[O'z kuchini yo'qotgan — OʻRQ-1025, 2025-yil 8-may]" },
            { no: 180, title: "Muassasa mol-mulkini tasarruf etish" },
            { no: 181, title: "Operativ boshqarish huquqining vujudga kelishi va bekor bo'lishi" },
          ],
        },
        {
          title: "15-BOB. MULK HUQUQINING VUJUDGA KELISHI VA UNING BEKOR BO'LISHI",
          articles: [
            { no: 182, title: "Mulk huquqining vujudga kelish asoslari" },
            { no: 183, title: "Mulkni yaratish va ko'paytirish" },
            { no: 184, title: "Bitim bo'yicha mol-mulkni olish" },
            { no: 185, title: "Shartnoma asosida mol-mulk oluvchida mulk huquqining vujudga kelish payti" },
            { no: 186, title: "Ashyolarni topshirish" },
            { no: 187, title: "Egalik qilish huquqini vujudga keltiruvchi muddat" },
            { no: 188, title: "Yer uchastkalariga bo'lgan mulk huquqi" },
            { no: 189, title: "Hamma yig'ib olishi mumkin bo'lgan ashyolarni mulkka aylantirish" },
            { no: 190, title: "Moddiy madaniy meros obyektlarini xo'jasizlarcha saqlash" },
            { no: 191, title: "Egasiz ashyo" },
            { no: 192, title: "Topilma" },
            { no: 193, title: "Topilmaga egalik huquqini olish" },
            { no: 194, title: "Topilma bilan bog'liq xarajatlarni to'lash va ashyoni topib olgan shaxsni taqdirlash" },
            { no: 195, title: "Qarovsiz hayvonlar" },
            { no: 196, title: "Xazina" },
            { no: 197, title: "Mulk huquqining bekor bo'lish asoslari" },
            { no: 198, title: "Mol-mulkni tugatish va hisobdan chiqarish" },
            { no: 199, title: "Mol-mulkni mulkdordan olib qo'yish" },
            { no: 200, title: "Qarzni nizosiz tartibda undirib olish" },
            { no: 201, title: "Qimmatbaho metallar va toshlarga mulk huquqining vujudga kelish hamda bekor bo'lish xususiyatlari" },
            { no: 202, title: "Natsionalizatsiya" },
            { no: 203, title: "Rekvizitsiya" },
            { no: 204, title: "Musodara" },
            { no: 205, title: "Mol-mulkni olib qo'yish chog'ida uning qiymatini aniqlash va zararlarni undirib olish huquqi" },
            { no: 206, title: "Mulkdorning mol-mulkini bevosita olib qo'yishga qaratmagan holda mulk huquqining bekor qilinishi" },
          ],
        },
        {
          title: "16-BOB. XUSUSIY MULK",
          articles: [
            { no: 207, title: "Xususiy mulk huquqi" },
            { no: 208, title: "Xususiy mulk huquqining subyektlari" },
            { no: 209, title: "Xususiy mulk huquqining obyektlari" },
            { no: 210, title: "Uy-joy (kvartira)ga mulk huquqining vujudga kelish tartibi" },
            { no: 211, title: "Ko'p kvartirali uydagi turar joylar va yashash uchun mo'ljallanmagan joylar mulkdorlarining umumiy mol-mulki" },
            { no: 212, title: "O'zboshimchalik bilan imorat qurish va uning oqibatlari" },
          ],
        },
        {
          title: "17-BOB. OMMAVIY MULK",
          articles: [
            { no: 213, title: "Ommaviy mulk tushunchasi" },
            { no: 214, title: "Respublika mulki" },
            { no: 215, title: "Munitsipal mulk" },
          ],
        },
        {
          title: "18-BOB. UMUMIY MULK",
          articles: [
            { no: 216, title: "Umumiy mulk tushunchasi va uning vujudga kelish asoslari" },
            { no: 217, title: "Ulushli mulkdagi ulushlarni aniqlash" },
            { no: 218, title: "Ulushli mulkdagi mol-mulkni tasarruf etish" },
            { no: 219, title: "Ulushli mulkdagi umumiy mol-mulkka egalik qilish va undan foydalanish" },
            { no: 220, title: "Ulushli mulkdagi mol-mulkdan foydalanish natijasida keladigan hosil, mahsulot va daromadlar" },
            { no: 221, title: "Umumiy ulushli mulkdagi mol-mulkni saqlash xarajatlarini taqsimlash" },
            { no: 222, title: "Umumiy mulk huquqidagi ulushning shartnoma bo'yicha oluvchiga o'tish payti" },
            { no: 223, title: "Ulushli mulkdagi mol-mulkni taqsimlash va undan ulush ajratish" },
            { no: 224, title: "Imtiyozli sotib olish huquqi" },
            { no: 225, title: "Birgalikdagi mulk bo'lgan mol-mulkka egalik qilish, undan foydalanish va uni tasarruf etish" },
            { no: 226, title: "Birgalikdagi mulk bo'lgan mol-mulkni taqsimlash va undan ulush ajratish" },
            { no: 227, title: "Undiruvni umumiy mol-mulkdagi ulushga qaratish" },
          ],
        },
        {
          title: "19-BOB. MULK HUQUQINI VA BOSHQA ASHYOVIY HUQUQLARNI HIMOYA QILISH",
          articles: [
            { no: 228, title: "Mol-mulkni boshqa shaxsning qonunsiz egaligidan talab qilib olish (vindikatsiya)" },
            { no: 229, title: "Mol-mulkni insofli egallovchidan talab qilib olish" },
            { no: 230, title: "Mol-mulk boshqa shaxsning qonunsiz egaligidan talab qilib olinganda daromadlar va xarajatlarni to'lash" },
            { no: 231, title: "Mulkdorning huquqlarini egalik qilishdan mahrum etish bilan bog'liq bo'lmagan huquqbuzarliklardan himoya qilish (negator da'vo)" },
            { no: 232, title: "Mulkdor bo'lmagan eganing huquqlarini himoya qilish" },
            { no: 233, title: "Mulk huquqining qonunga muvofiq bekor bo'lish oqibatlari" },
          ],
        },
      ],
    },

    // ========================================================
    // III BO'LIM — MAJBURIYAT HUQUQI
    // ========================================================
    {
      title: "III BO'LIM. MAJBURIYAT HUQUQI",
      subsections: [
        {
          title: "1-Kichik bo'lim. MAJBURIYATLAR TO'G'RISIDA UMUMIY QOIDALAR",
          chapters: [
            {
              title: "20-BOB. MAJBURIYAT TUSHUNCHASI VA TARAFLARI",
              articles: [
                { no: 234, title: "Majburiyat tushunchasi va uning vujudga kelish asoslari" },
                { no: 235, title: "Majburiyatning taraflari" },
              ],
            },
            {
              title: "21-BOB. MAJBURIYATLARNI BAJARISH",
              articles: [
                { no: 236, title: "Umumiy qoidalar" },
                { no: 237, title: "Majburiyatni bajarishdan bir tomonlama bosh tortishga yo'l qo'yilmasligi" },
                { no: 238, title: "Majburiyatning kelishilgan va maqbul usulda bajarilishi" },
                { no: 239, title: "Majburiyatning qismlarga bo'lib bajarilishi" },
                { no: 240, title: "Majburiyatning tegishli shaxs uchun bajarilishi" },
                { no: 241, title: "Majburiyatni bajarishni uchinchi shaxs zimmasiga yuklash" },
                { no: 242, title: "Majburiyatni bajarish muddati" },
                { no: 243, title: "Majburiyatni muddatidan ilgari bajarish" },
                { no: 244, title: "Majburiyatni bajarishni kechiktirish yoki uni bo'lib-bo'lib bajarish" },
                { no: 245, title: "Pul majburiyatlarining valyutasi" },
                { no: 246, title: "Majburiyatni bajarish joyi" },
                { no: 247, title: "Fuqaroning ta'minoti uchun to'lanadigan summani ko'paytirish" },
                { no: 248, title: "Pul majburiyati bo'yicha talablarni qondirish navbati" },
                { no: 249, title: "Qarzni depozitga qo'yish yo'li bilan majburiyatni bajarish" },
                { no: 250, title: "Muqobil majburiyatni bajarish" },
                { no: 251, title: "Bir necha kreditor yoki bir necha qarzdor ishtirok etadigan majburiyatni bajarish" },
                { no: 252, title: "Solidar qarzdorlar majburiyati bo'yicha kreditorning huquqlari" },
                { no: 253, title: "Solidar qarzdorlarning kreditor talablariga qarshi e'tirozlari" },
                { no: 254, title: "Solidar majburiyatning qarzdorlardan biri tomonidan bajarilishi" },
                { no: 255, title: "Solidar talablar" },
                { no: 256, title: "Majburiyatlarni muqobil suratda bajarish" },
                { no: 257, title: "Majburiyatning bajarganligini tasdiqlash" },
                { no: 258, title: "Majburiyat bajarilganligini tasdiqlash haqidagi talabni bajarmaslik oqibatlari" },
              ],
            },
            {
              title: "22-BOB. MAJBURIYATLARNING BAJARILISHINI TA'MINLASH",
              subchapters: [
                {
                  title: "Umumiy",
                  articles: [
                    { no: 259, title: "Umumiy qoidalar" },
                    { no: '259¹', title: "Kreditorlarning talablarini qarzdorning majburiyatlar bajarilishining ta'minoti sifatida berilgan mol-mulki yoki yer uchastkasini ijaraga olish huquqi hisobidan qanoatlantirish" },
                  ],
                },
                {
                  title: "1-§. Neustoyka",
                  articles: [
                    { no: 260, title: "Neustoyka tushunchasi" },
                    { no: 261, title: "Neustoyka shakllari" },
                    { no: 262, title: "Neustoyka to'g'risidagi kelishuvning shakli" },
                    { no: 263, title: "Qonuniy neustoyka" },
                  ],
                },
                {
                  title: "2-§. Garov",
                  articles: [
                    { no: 264, title: "Garov tushunchasi va uning vujudga kelish asoslari" },
                    { no: 265, title: "Garov turlari" },
                    { no: 266, title: "Garovga qo'yuvchi" },
                    { no: 267, title: "Garov narsasi" },
                    { no: 268, title: "Garov bilan ta'minlanadigan talab" },
                    { no: 269, title: "Garovga qo'yilgan mol-mulkning garovga oluvchiga berilishi va berilmasligi" },
                    { no: 270, title: "Garov huquqining vujudga kelishi" },
                    { no: 271, title: "Garov to'g'risidagi shartnoma, uning shakli va shartnomani ro'yxatdan o'tkazish" },
                    { no: 272, title: "Garovga oluvchining huquqlari joriy qilinadigan mol-mulk" },
                    { no: 273, title: "Navbatdagi garov" },
                    { no: 274, title: "Garovga qo'yilgan mol-mulkni saqlash va asrash" },
                    { no: 275, title: "Garov narsasini almashtirish va tiklash" },
                    { no: 276, title: "Garov narsasini almashtirish va tiklash" },
                    { no: 277, title: "Garov narsasidan foydalanish va uni tasarruf etish" },
                    { no: 278, title: "Garovga oluvchining garov narsasiga bo'lgan o'z huquqlarini himoya qilishi" },
                    { no: 279, title: "Undiruvni garovga qo'yilgan mol-mulkka qaratish asoslari" },
                    { no: 280, title: "Undiruvni garovga qo'yilgan mol-mulkka qaratish tartibi" },
                    { no: 281, title: "Garovga qo'yilgan mol-mulkni sotish" },
                    { no: 282, title: "Garov bilan ta'minlangan majburiyatni muddatidan ilgari bajarish va undiruvni garovga qo'yilgan mol-mulkka qaratish" },
                    { no: 283, title: "Garovning bekor bo'lishi" },
                    { no: 284, title: "Garovga qo'yilgan mol-mulkka bo'lgan huquq boshqa shaxsga o'tganida garovning saqlanishi" },
                    { no: 285, title: "Garovga qo'yilgan mol-mulkni majburiy ravishda olib qo'yishning oqibatlari" },
                    { no: 286, title: "Garov to'g'risidagi shartnoma bo'yicha huquqlardan boshqa shaxs foydasiga voz kechish" },
                    { no: 287, title: "Garov bilan ta'minlangan majburiyat bo'yicha qarzni boshqa shaxsga o'tkazish" },
                    { no: 288, title: "Muomaladagi tovarlar garovi" },
                    { no: 289, title: "Ashyolarning lombardda garovga qo'yilishi" },
                  ],
                },
                {
                  title: "3-§. Ushlab qolish",
                  articles: [
                    { no: 290, title: "Ushlab qolish asoslari" },
                    { no: 291, title: "Talablarni ushlab qolingan ashyo hisobidan qondirish" },
                  ],
                },
                {
                  title: "4-§. Kafillik",
                  articles: [
                    { no: 292, title: "Kafillik shartnomasi" },
                    { no: 293, title: "Kafilning javobgarligi" },
                    { no: 294, title: "Kafilga nisbatan da'vo qo'zg'atilgan taqdirda uning huquq va burchlari" },
                    { no: 295, title: "Majburiyatni bajargan kafilning huquqlari" },
                    { no: 296, title: "Qarzdor majburiyatini bajarganligi haqida kafilni xabardor qilish" },
                    { no: 297, title: "Kafilning xizmatlariga haq to'lash" },
                    { no: 298, title: "Kafillikning bekor bo'lishi" },
                  ],
                },
                {
                  title: "5-§. Kafolat",
                  articles: [
                    { no: 299, title: "Kafolat tushunchasi" },
                    { no: 300, title: "Prinsipalning majburiyatlarini kafolat bilan ta'minlash" },
                    { no: 301, title: "Kafolatning asosiy majburiyatdan mustaqilligi" },
                    { no: 302, title: "Kafolatning chaqirib olinmasligi" },
                    { no: 303, title: "Kafolat bo'yicha huquqlarning boshqa shaxsga o'tkazilmasligi" },
                    { no: 304, title: "Kafolatning kuchga kirishi" },
                    { no: 305, title: "Kafolat bo'yicha talab taqdim etish" },
                    { no: 306, title: "Benefitsiarning talabini ko'rib chiqishda kafilning majburiyatlari" },
                    { no: 307, title: "Kafilning benefitsiar talabini qondirishni rad etishi" },
                    { no: 308, title: "Kafil majburiyatlarining chegaralari" },
                    { no: 309, title: "Kafolatning bekor bo'lishi" },
                    { no: 310, title: "Kafilning prinsipalga regress talablari" },
                  ],
                },
                {
                  title: "6-§. Zakalat",
                  articles: [
                    { no: 311, title: "Zakalat tushunchasi. Zakalat to'g'risidagi kelishuv shakli" },
                    { no: 312, title: "Zakalat bilan ta'minlangan majburiyatni bekor qilish va bajarmaslik oqibatlari" },
                  ],
                },
              ],
            },
            {
              title: "23-BOB. MAJBURIYATDAGI SHAXSLARNING O'ZGARISHI",
              articles: [
                { no: 313, title: "Kreditor huquqlarining boshqa shaxsga o'tish asoslari va tartibi" },
                { no: 314, title: "Boshqa shaxslarga o'tishi mumkin bo'lmagan huquqlar" },
                { no: 315, title: "Boshqa shaxsga o'tadigan kreditor huquqlarining hajmi" },
                { no: 316, title: "Yangi kreditor huquqlarining isboti" },
                { no: 317, title: "Qarzdorning yangi kreditor talabiga qarshi e'tirozlari" },
                { no: 318, title: "Kreditor huquqlarining qonun asosida boshqa shaxsga o'tishi" },
                { no: 319, title: "Talabdan boshqa shaxs foydasiga voz kechish shartlari" },
                { no: 320, title: "Talabdan boshqa shaxs foydasiga voz kechish shakli" },
                { no: 321, title: "Talabdan boshqa shaxs foydasiga voz kechgan kreditorning javobgarligi" },
                { no: 322, title: "Qarzni boshqa shaxsga o'tkazish" },
                { no: 323, title: "Qarzni va ijroni bir paytda boshqa shaxsga o'tkazish" },
              ],
            },
            {
              title: "24-BOB. MAJBURIYATLARNI BUZGANLIK UCHUN JAVOBGARLIK",
              articles: [
                { no: 324, title: "Qarzdorning zararni to'lash majburiyati" },
                { no: 325, title: "Neustoyka va zarar" },
                { no: 326, title: "Neustoykani kamaytirish" },
                { no: 327, title: "Pul majburiyatini bajarmaganlik uchun javobgarlik" },
                { no: 328, title: "Majburiyatning qarzdor hisobidan bajarilishi" },
                { no: 329, title: "Subsidiar javobgarlik" },
                { no: 330, title: "Javobgarlik va majburiyatni asl holida bajarish" },
                { no: 331, title: "Xususiy belgili ashyoni topshirish majburiyatini bajarmaslik oqibatlari" },
                { no: 332, title: "Majburiyatlar bo'yicha javobgarlik hajmini cheklash" },
                { no: 333, title: "Majburiyatlarni buzganlik uchun javobgarlik asoslari" },
                { no: 334, title: "Uchinchi shaxslarning harakatlari uchun qarzdorning javobgarligi" },
                { no: 335, title: "Kreditorning aybi" },
                { no: 336, title: "Ikki taraflama shartnomani bajarmaslik oqibatlari" },
                { no: 337, title: "Ijroning qarzdor va kreditor tomonidan kechiktirib yuborilishi" },
                { no: 338, title: "Kreditorning ijroni kechiktirib yuborish oqibatlari" },
                { no: 339, title: "Ijroning kechiktirib yuborilganligi uchun kreditorni javobgarlikdan ozod qilish" },
              ],
            },
            {
              title: "25-BOB. MAJBURIYATLARNING BEKOR BO'LISHI",
              articles: [
                { no: 340, title: "Majburiyatlarning bekor bo'lish asoslari" },
                { no: 341, title: "Majburiyatning bajarilishi bilan bekor bo'lishi" },
                { no: 342, title: "Voz kechish haqi" },
                { no: 343, title: "Hisobga o'tkazish bilan majburiyatning bekor bo'lishi" },
                { no: 344, title: "Hisobga o'tkazishga yo'l qo'yilmasligi" },
                { no: 345, title: "Talabdan boshqa shaxs foydasiga voz kechilganida hisobga o'tkazish" },
                { no: 346, title: "Qarzdor bilan kreditor bir shaxs bo'lib qolganida majburiyatning bekor bo'lishi" },
                { no: 347, title: "Majburiyat yangilanishi bilan uning bekor bo'lishi" },
                { no: 348, title: "Qarzdan voz kechish" },
                { no: 349, title: "Bajarish mumkin bo'lmaganligi tufayli majburiyatning bekor bo'lishi" },
                { no: 350, title: "Majburiyatning davlat organi hujjati asosida bekor bo'lishi" },
                { no: 351, title: "Fuqaro vafot etishi bilan majburiyatning bekor bo'lishi" },
                { no: 352, title: "Yuridik shaxs tugatilishi bilan majburiyatning bekor bo'lishi" },
              ],
            },
          ],
        },
        {
          title: "2-Kichik bo'lim. SHARTNOMA TO'G'RISIDA UMUMIY QOIDALAR",
          chapters: [
            {
              title: "26-BOB. SHARTNOMA TUSHUNCHASI VA SHARTLARI",
              articles: [
                { no: 353, title: "Shartnoma tushunchasi" },
                { no: 354, title: "Shartnoma tuzish erkinligi" },
                { no: 355, title: "Haq evaziga va tekinga tuziladigan shartnomalar" },
                { no: 356, title: "Baho" },
                { no: 357, title: "Shartnomaning amal qilishi" },
                { no: 358, title: "Ommaviy shartnoma" },
                { no: '358¹', title: "Korporativ shartnoma" },
                { no: 359, title: "Shartnomaning namunaviy shartlari" },
                { no: 360, title: "Qo'shilish shartnomasi" },
                { no: 361, title: "Dastlabki shartnoma" },
                { no: 362, title: "Uchinchi shaxs foydasiga tuziladigan shartnoma" },
                { no: 363, title: "Shartnomani sharhlash" },
              ],
            },
            {
              title: "27-BOB. SHARTNOMA TUZISH",
              articles: [
                { no: 364, title: "Shartnoma tuzish to'g'risidagi asosiy qoidalar" },
                { no: 365, title: "Shartnomaning tuzilish payti" },
                { no: 366, title: "Shartnomaning shakli" },
                { no: 367, title: "Oferta" },
                { no: 368, title: "Ofertaning chaqirib olinmasligi" },
                { no: 369, title: "Ofertaga taklif etish. Ommaviy oferta" },
                { no: 370, title: "Aksept" },
                { no: 371, title: "Akseptni chaqirib olish" },
                { no: 372, title: "Aksept muddati ko'rsatilgan oferta asosida shartnoma tuzish" },
                { no: 373, title: "Aksept muddati ko'rsatilmagan oferta asosida shartnoma tuzish" },
                { no: 374, title: "Kechikib olingan aksept" },
                { no: 375, title: "Boshqa shartlar asosidagi aksept" },
                { no: 376, title: "Shartnomaning tuzilgan joyi" },
                { no: 377, title: "Majburiy tartibda shartnoma tuzish" },
                { no: 378, title: "Shartnoma oldidan bo'ladigan nizolar" },
                { no: 379, title: "Kimoshdi savdosida shartnoma tuzish" },
                { no: 380, title: "Kimoshdi savdosini tashkil etish va uni o'tkazish tartibi" },
                { no: 381, title: "Kimoshdi savdosini o'tkazish qoidalarini buzish oqibatlari" },
              ],
            },
            {
              title: "28-BOB. SHARTNOMANI O'ZGARTIRISH VA BEKOR QILISH",
              articles: [
                { no: 382, title: "Shartnomani o'zgartirish va bekor qilish asoslari" },
                { no: 383, title: "Vaziyat jiddiy o'zgarishi munosabati bilan shartnomani o'zgartirish va bekor qilish" },
                { no: 384, title: "Shartnomani o'zgartirish va bekor qilish tartibi" },
                { no: 385, title: "Shartnomani o'zgartirish va bekor qilishning oqibatlari" },
              ],
            },
          ],
        },
      ],
    },
  ],
};

module.exports = CIVIL_CODE_TOC;
