// server/legal-content/uz/civilCode_part2.js
// ============================================================================
// O'ZBEKISTON RESPUBLIKASINING FUQAROLIK KODEKSI — 2-QISM (386–1199 moddalar)
//
// Manba: lex.uz (https://lex.uz/docs/-180552)
// Qabul qilingan: 29.08.1996 — Kuchga kirish: 01.03.1997
// So'nggi tekshirilgan: 2026-yil 30-iyun
//
// BOB GURUHLARI (NRM.uz dan tasdiqlangan):
//   29-bob:      386–496   (Oldi-sotdi)
//   30–34 bob:   497–599   (Mena, Hadya, Renta, Umrbod ta'minlash, Ijara)
//   35–37 bob:   600–702   (Uy-joy ijarasi, Bepul foydalanish, Pudrat)
//   38–44 bob:   703–789   (Tashish, Ekspeditsiya, Qarz, Kredit, Faktorinq,
//                           Bank hisobraqi/omonati, Dalolat)
//   45–49 bob:   790–861   (Cheklar/Veksil, Topshiriq, Komissiya/Vositachilik,
//                           Ishonchli boshqarish, Oddiy shirkat)
//   50–58 bob:   862–1030  (Kompleks litsenziya, Omonat saqlash, Sug'urta,
//                           Zarar yetkazish, Asossiz boyib ketish)
//   59–65 bob:  1031–1111  (IV bo'lim: Intellektual mulk)
//   66–69 bob:  1112–1157  (V bo'lim: Vorislik huquqi)
//   70–71 bob:  1158–1199  (VI bo'lim: Xalqaro xususiy huquq)
// ============================================================================

const CIVIL_CODE_PART2_TOC = {
  key: 'civil2',
  name: "Fuqarolik kodeksi (2-qism)",
  officialName: "O'zbekiston Respublikasining Fuqarolik kodeksi (ikkinchi qism)",
  url: 'https://lex.uz/docs/-180552',
  adoptedDate: '1996-08-29',
  effectiveDate: '1997-03-01',
  lastChecked: '2026-06-30',
  detailedToc: true,
  tocSections: [

    // ========================================================
    // III BO'LIM (davomi) — MAJBURIYAT HUQUQI
    // 3-kichik bo'lim: SHARTNOMALARNING AYRIM TURLARI
    // ========================================================
    {
      title: "III BO'LIM (davomi). MAJBURIYAT HUQUQI — 3-kichik bo'lim: SHARTNOMALARNING AYRIM TURLARI",
      chapters: [

        // --------------------------------------------------
        // 29-BOB: OLDI-SOTDI (386–496)
        // --------------------------------------------------
        {
          title: "29-BOB. OLDI-SOTDI",
          subchapters: [
            {
              title: "1-§. Umumiy qoidalar (386–424)",
              articles: [
                { no: 386, title: "Oldi-sotdi shartnomasi" },
                { no: 387, title: "Shartnomaning tovar to'g'risidagi sharti" },
                { no: 388, title: "Tovarni topshirish majburiyati" },
                { no: 389, title: "Tovarni topshirish majburiyatini bajarish muddati" },
                { no: 390, title: "Tovarni muddatidan ilgari topshirish" },
                { no: 391, title: "Tovarni yetkazib berish majburiyati" },
                { no: 392, title: "Mol-mulkni saqlab qolish majburiyati" },
                { no: 393, title: "Tovar uchun haq to'lash majburiyati" },
                { no: 394, title: "To'lov muddati" },
                { no: 395, title: "To'lovni kechiktirish" },
                { no: 396, title: "To'lovni muddatidan oldin amalga oshirish" },
                { no: 397, title: "Tovarga mansub ashyolar yoki hujjatlarni topshirish" },
                { no: 398, title: "Tovarning miqdori" },
                { no: 399, title: "Tovarni miqdoridan kam yoki ortiq yetkazib berishning oqibatlari" },
                { no: 400, title: "Tovarning assortimenti" },
                { no: 401, title: "Assortiment shartini buzishning oqibatlari" },
                { no: 402, title: "Tovarning sifati" },
                { no: 403, title: "Sotuvchining tovar sifati uchun kafolati" },
                { no: 404, title: "Tovarning muddati" },
                { no: 405, title: "Muddati o'tgan tovarni sotishning oqibatlari" },
                { no: 406, title: "Tovarni tekshirish" },
                { no: 407, title: "Tovarning sifatini tekshirish" },
                { no: 408, title: "Tegishli darajada bo'lmagan tovar yetkazib berish to'g'risida sotuvchini xabardor qilish" },
                { no: 409, title: "Sifati shartnoma talablariga javob bermaydigan tovarni yetkazib berishning oqibatlari" },
                { no: 410, title: "Tovar sifatining kafolat muddati" },
                { no: 411, title: "Tovar sifatining xizmat muddati" },
                { no: 412, title: "Kamchiliklar aniqlangan taqdirda sotib oluvchining huquqlari" },
                { no: 413, title: "Tovarning to'liqligi" },
                { no: 414, title: "To'liq bo'lmagan tovar yetkazib berishning oqibatlari" },
                { no: 415, title: "Tovar to'plamining to'liqligi" },
                { no: 416, title: "Tovarning idishi va o'ralishi" },
                { no: 417, title: "Sotib oluvchining tovarni qabul qilish majburiyati" },
                { no: 418, title: "Tovarni qabul qilishdan bosh tortishning oqibatlari" },
                { no: 419, title: "Tovarni saqlab qolish majburiyati" },
                { no: 420, title: "Mulk huquqining o'tishi" },
                { no: 421, title: "Tasodifan nobud bo'lish xavfi" },
                { no: 422, title: "Tovarni sug'urtalash majburiyati" },
                { no: 423, title: "Tovarni sotib oluvchi huquqlarining uchinchi shaxs tomonidan buzilishi" },
                { no: 424, title: "Savdo bitimlarini qo'llashning xususiyatlari" },
              ],
            },
            {
              title: "2-§. Chakana oldi-sotdi (425–436)",
              articles: [
                { no: 425, title: "Chakana oldi-sotdi shartnomasi" },
                { no: 426, title: "Chakana oldi-sotdi shartnomasini tuzish" },
                { no: 427, title: "Chakana oldi-sotdi shartnomasini taklif qilish" },
                { no: 428, title: "Tovar narxi va uni to'lash" },
                { no: 429, title: "Tovarni ko'rsatib berish va ma'lumot berish" },
                { no: 430, title: "Tovarni sotib oluvchiga topshirish" },
                { no: 431, title: "To'lovni avval amalga oshirish sharti bilan tovar sotish" },
                { no: 432, title: "Namuna bo'yicha tovar sotish" },
                { no: 433, title: "Tovarni murojaat qilib olish usulida sotish" },
                { no: 434, title: "Tovar sifatiga qo'yiladigan talablar" },
                { no: 435, title: "Tegishli darajada bo'lmagan tovar yetkazib berish to'g'risida sotuvchini xabardor qilish" },
                { no: 436, title: "Sifati tegishli darajada bo'lmagan tovar sotib oluvchining huquqlari" },
              ],
            },
            {
              title: "3-§. Mahsulot yetkazib berish (437–456)",
              articles: [
                { no: 437, title: "Mahsulot yetkazib berish shartnomasi" },
                { no: 438, title: "Mahsulot yetkazib berish shartnomasi bo'yicha ta'minlovchining yetkazib berish muddatlari" },
                { no: 439, title: "Mahsulot yetkazib berish shartnomasini yangilash tartibi" },
                { no: 440, title: "Tovarlarni yetkazib berish tartibi" },
                { no: 441, title: "Topshirilgan tovarning hisobi" },
                { no: 442, title: "Tovarni olish" },
                { no: 443, title: "To'liq bo'lmagan miqdorda tovar yetkazib berishning oqibatlari" },
                { no: 444, title: "Assortimentga rioya qilmaslikning oqibatlari" },
                { no: 445, title: "Tovar sifatiga rioya qilmaslikning oqibatlari" },
                { no: 446, title: "Sinovdan o'tkazilishi shart bo'lgan tovarni yetkazib berish" },
                { no: 447, title: "Tovarning to'liqligiga rioya qilmaslik oqibatlari" },
                { no: 448, title: "Tovarni tara va o'rashga rioya qilmaslikning oqibatlari" },
                { no: 449, title: "Tovar uchun haq to'lash" },
                { no: 450, title: "Tovarni olib qolish" },
                { no: 451, title: "Bir tarafning shartnomani bajarmasligi yoki lozim darajada bajarmasligi oqibatida yetkazilgan zarar" },
                { no: 452, title: "Ta'minotchilar tomonidan o'xshash tovar narxidagi farqni undirib olish" },
                { no: 453, title: "Talablarni qondirish tartibi" },
                { no: 454, title: "Mahsulot yetkazib berish shartnomalarini o'zgartirish va bekor qilish" },
                { no: 455, title: "Mahsulot yetkazib berish shartnomalarini bir tomonlama to'xtatish" },
                { no: 456, title: "Hisob-kitob qilish tartibi" },
              ],
            },
            {
              title: "4-§. Tovarlar yetkazib berish to'g'risidagi davlat kontrakti (457–464)",
              articles: [
                { no: 457, title: "Tovarlar yetkazib berish to'g'risidagi davlat kontrakti" },
                { no: 458, title: "Davlat kontrakt tuzish asoslari" },
                { no: 459, title: "Davlat kontraktini tuzish tartibi" },
                { no: 460, title: "Davlat kontraktini tuzishdan bosh tortish" },
                { no: 461, title: "Tovarlarni yetkazib berish va sotib oluvchiga topshirish" },
                { no: 462, title: "Tovar uchun haq to'lash va tovarlarni moliyalashtirish" },
                { no: 463, title: "Tovarlarni yetkazib berish majburiyatlarini bajarmaganlik uchun javobgarlik" },
                { no: 464, title: "Buyurtmachi tomonidan shartnomaviy majburiyatlarni bajarmaganlik uchun javobgarlik" },
              ],
            },
            {
              title: "5-§. Kontraktatsiya (465–467)",
              articles: [
                { no: 465, title: "Kontraktatsiya shartnomasi" },
                { no: 466, title: "Qishloq xo'jaligi mahsulotlarini yetkazib berishning xususiyatlari" },
                { no: 467, title: "Mahsulot yetkazib beruvchining xo'jalik faoliyati" },
              ],
            },
            {
              title: "6-§. Energiya ta'minoti (468–478)",
              articles: [
                { no: 468, title: "Energiya ta'minoti shartnomasi" },
                { no: 469, title: "Energiya ta'minoti shartnomasi bo'yicha energiyaning miqdori va sifati" },
                { no: 470, title: "Energiya ta'minoti shartnomasi bo'yicha energiyani topshirish tartibi" },
                { no: 471, title: "Energiya ta'minoti shartnomasini yangilash va o'zgartirish" },
                { no: 472, title: "Energiya ta'minotini to'xtatish yoki cheklash" },
                { no: 473, title: "Energiya ta'minoti bo'yicha ma'lumot berish" },
                { no: 474, title: "Energiya ta'minoti shartnomasini buzganlik uchun javobgarlik" },
                { no: 475, title: "Energiya ta'minoti shartnomasini bekor qilish" },
                { no: 476, title: "Qurilmalarga energiya yetkazib berishning xususiyatlari" },
                { no: 477, title: "Energiya bilan foydalanish shartnomalari" },
                { no: 478, title: "Boshqa tovarlarni yetkazib berishga nisbatan qoidalarni qo'llash" },
              ],
            },
            {
              title: "7-§. Ko'chmas mulkni sotish (479–488)",
              articles: [
                { no: 479, title: "Ko'chmas mulkni sotish shartnomasi" },
                { no: 480, title: "Ko'chmas mulkni sotish narxi" },
                { no: 481, title: "Ko'chmas mulkni topshirish" },
                { no: 482, title: "Mulk huquqining o'tishi" },
                { no: 483, title: "Yer uchastkasida joylashgan ko'chmas mulkni sotish" },
                { no: 484, title: "Ko'chmas mulk joylashgan yer uchastkasini sotish" },
                { no: 485, title: "Ko'chmas mulkni sotish shartnomasining maxsus shartlari" },
                { no: 486, title: "Ko'chmas mulk sifatini tekshirish" },
                { no: 487, title: "Ko'chmas mulkni uchinchi shaxslar huquqlari bilan yuk ostida sotish" },
                { no: 488, title: "Mulk uchun haq to'lash majburiyatini bajarmaslikning oqibatlari" },
              ],
            },
            {
              title: "8-§. Korxonani sotish (489–496)",
              articles: [
                { no: 489, title: "Korxonani sotish shartnomasi" },
                { no: 490, title: "Korxonani notarial tasdiqlash va ro'yxatdan o'tkazish" },
                { no: 491, title: "Korxonani sotish to'g'risida kreditorlarni xabardor qilish" },
                { no: 492, title: "Korxona kreditorlarining huquqlari" },
                { no: 493, title: "Korxonani topshirish" },
                { no: 494, title: "Korxonani topshirganidan keyin mulk huquqining o'tishi" },
                { no: 495, title: "Korxonani sotib oluvchi tomonidan qabul qilingan korxona tarkibidagi kamchiliklar uchun oqibatlar" },
                { no: 496, title: "Korxonani sotish shartnomasining xususiyatlarini qo'llash" },
              ],
            },
          ],
        },

        // --------------------------------------------------
        // 30–34 BOB (497–599)
        // --------------------------------------------------
        {
          title: "30-BOB. MENA (AYIRBOSHLASH) (497–501)",
          articles: [
            { no: 497, title: "Mena shartnomasi" },
            { no: 498, title: "Tovarlarning barobar emasligi" },
            { no: 499, title: "Mulk huquqining o'tishi" },
            { no: 500, title: "Uchinchi shaxslarning mol-mulkka huquqlari" },
            { no: 501, title: "Oldi-sotdi qoidalarini qo'llash" },
          ],
        },
        {
          title: "31-BOB. HADYA (502–511)",
          articles: [
            { no: 502, title: "Hadya shartnomasi" },
            { no: 503, title: "Hadya etishni va'da qilish" },
            { no: 504, title: "Hadyaning taqiqlangan holatlari" },
            { no: 505, title: "Hadyani cheklash" },
            { no: 506, title: "Hadya oluvchi o'rniga uchinchi shaxs foydasiga hadya" },
            { no: 507, title: "Hadya shartnomasi shakli" },
            { no: 508, title: "Hadya shartnomasini bajarishdan bosh tortish va hadyani bekor qilish mumkin bo'lmagan hollar" },
            { no: 509, title: "Kamchiliklari bo'lgan mol-mulkni hadya qilish oqibatlari" },
            { no: 510, title: "Hadya va'da qilinganida huquqiy vorislik" },
            { no: 511, title: "Hadyani bekor qilish" },
          ],
        },
        {
          title: "32-BOB. RENTA VA UMRBOD TA'MINLASH (512–529)",
          subchapters: [
            {
              title: "1-§. Renta to'lash sharti bilan mol-mulk topshirish (512–529)",
              articles: [
                { no: 512, title: "Renta shartnomasi" },
                { no: 513, title: "Renta shartnomasi shakli va davlat ro'yxatidan o'tkazish" },
                { no: 514, title: "Renta shartnomasi bo'yicha mol-mulkni topshirish" },
                { no: 515, title: "Renta to'lovlari bilan ta'minlash" },
                { no: 516, title: "Renta shartnomasi bo'yicha mol-mulk uchinchi shaxsga o'tganida javobgarlik" },
                { no: 517, title: "Renta to'lashni to'xtatish" },
                { no: 518, title: "Doimiy renta" },
                { no: 519, title: "Doimiy renta to'lovlari" },
                { no: 520, title: "Doimiy renta to'lovlarini kechiktirish uchun javobgarlik" },
                { no: 521, title: "Doimiy rentani to'lashdan voz kechish huquqi" },
                { no: 522, title: "Doimiy renta to'lashni to'xtatish" },
                { no: 523, title: "Doimiy renta shartnomasi bo'yicha mol-mulkni qaytarib berish" },
                { no: 524, title: "Doimiy renta to'lash sharti bilan topshirilgan mol-mulkning tasodifan nobud bo'lish yoki tasodifan buzilish xavfi" },
                { no: 525, title: "Umrbod renta" },
                { no: 526, title: "Umrbod renta to'lovlari" },
                { no: 527, title: "Renta to'lovlarini kechiktirish uchun javobgarlik" },
                { no: 528, title: "Renta oluvchining talabiga ko'ra umrbod renta shartnomasini bekor qilish" },
                { no: 529, title: "Renta to'lash sharti bilan topshirilgan mol-mulkning tasodifan nobud bo'lish yoki tasodifan buzilish xavfi" },
              ],
            },
          ],
        },
        {
          title: "33-BOB. UMRBOD TA'MINLASH SHARTI BILAN UY-JOY (KVARTIRA)NI BOSHQA SHAXSGA BERISH (530–534)",
          articles: [
            { no: 530, title: "Umrbod ta'minlash sharti bilan uy-joy (kvartira)ni boshqa shaxsga berish shartnomasi" },
            { no: 531, title: "Umrbod ta'minlash sharti bilan uy-joy (kvartira)ni boshqa shaxsga berish shartnomasining shakli va shartlari" },
            { no: 532, title: "Ta'minot miqdori" },
            { no: 533, title: "Mol-mulkni tasarruf etish va foydalanish" },
            { no: 534, title: "Ta'minlovchi tomonidan shartnomani bekor qilish" },
          ],
        },
        {
          title: "34-BOB. IJARA (535–599)",
          subchapters: [
            {
              title: "1-§. Umumiy qoidalar (535–584)",
              articles: [
                { no: 535, title: "Ijara shartnomasi" },
                { no: 536, title: "Ijaraga beruvchi" },
                { no: 537, title: "Ijara ob'ekti" },
                { no: 538, title: "Ijaraga olingan mol-mulk to'g'risida ma'lumot berish" },
                { no: 539, title: "Mol-mulkni topshirish muddati" },
                { no: 540, title: "Ijaraga olingan mol-mulkni topshirish" },
                { no: 541, title: "Ijara muddati" },
                { no: 542, title: "Mol-mulkdan foydalanish" },
                { no: 543, title: "Mol-mulkni saqlash" },
                { no: 544, title: "Ijarachilik haqi" },
                { no: 545, title: "Ijaraga oluvchining mol-mulkni qayta ta'mirlash majburiyati" },
                { no: 546, title: "Mol-mulkni joriy ta'mirlash" },
                { no: 547, title: "Mol-mulkni kapital ta'mirlash" },
                { no: 548, title: "Ijaraga oluvchining mol-mulkni yaxshilash huquqlari" },
                { no: 549, title: "Ijaraga berishning bekor bo'lishi" },
                { no: 550, title: "Mol-mulkni qaytarish majburiyati" },
                { no: 551, title: "Mol-mulkni qaytarmaslikning oqibatlari" },
                { no: 552, title: "Ijaraga oluvchiga mulk huquqining o'tishi" },
                { no: 553, title: "Ijaraga olingan mol-mulkka bo'lgan huquqni uchinchi shaxsga o'tkazish" },
                { no: 554, title: "Ikkilamchi ijara" },
                { no: 555, title: "Ijara huquqlarini garovga qo'yish" },
                { no: 556, title: "Ijaraga berishning bekor bo'lishi" },
                { no: 557, title: "Ijaraga beruvchi ijara munosabatlaridan kelib chiqadigan da'volar bo'yicha imtiyozli huquqlari" },
                { no: 558, title: "Ijaraga berishni muddatidan oldin bekor qilish" },
                { no: 559, title: "Ijaraga oluvchi tomonidan shartnomasini muddatidan oldin bekor qilish" },
                { no: 560, title: "Ijaraga berishning muddati o'tgandan keyin yangilash" },
                { no: 561, title: "Yangi muddatga ijara shartnomasini tuzishda imtiyozli huquq" },
                { no: 562, title: "Korxonani ijaraga berish" },
                { no: 563, title: "Korxonani ijaraga berishning xususiyatlari" },
                { no: 564, title: "Korxonani ijaraga oluvchining huquqlari" },
                { no: 565, title: "Ijaraga olingan korxona kreditorlarining huquqlari" },
                { no: 566, title: "Ijaraga olingan korxonani qaytarish" },
                { no: 567, title: "Korxonani ijaraga berish shartnomasiga qoidalarni qo'llash" },
                { no: 568, title: "Transport vositalarini ijaraga berish" },
                { no: 569, title: "Transport vositalarini haydovchi bilan ijaraga berish shartnomasi" },
                { no: 570, title: "Transport vositasini haydovchi bilan ijaraga berish bo'yicha ijaraga beruvchining majburiyatlari" },
                { no: 571, title: "Transport vositasidan foydalanish uchun xarajatlarni taqsimlash" },
                { no: 572, title: "Transport vositasi haydovchi bilan ijaraga berilganida uchinchi shaxslarga zarar yetkazganlik uchun javobgarlik" },
                { no: 573, title: "Transport vositasini haydovchisiz ijaraga berish shartnomasi" },
                { no: 574, title: "Transport vositasini haydovchisiz ijaraga berishda ijaraga oluvchi majburiyatlari" },
                { no: 575, title: "Transport vositasini haydovchisiz ijaraga berilganida uchinchi shaxslarga zarar yetkazganlik uchun javobgarlik" },
                { no: 576, title: "Binolar va inshootlarni ijaraga berish shartnomasi" },
                { no: 577, title: "Bino yoki inshootni ijaraga berishning shakli va ro'yxatdan o'tkazish" },
                { no: 578, title: "Bino yoki inshoot topshiriladigan yer uchastkasiga bo'lgan huquqlar" },
                { no: 579, title: "Bino yoki inshoot ijarasi narxi" },
                { no: 580, title: "Bino yoki inshootni topshirish va qaytarish" },
                { no: 581, title: "Ijaraga olingan binolardan foydalanish" },
                { no: 582, title: "Bino ijarasiga nisbatan uy-joy ijarasi qoidalarini qo'llamaslik" },
                { no: 583, title: "Prokat" },
                { no: 584, title: "Prokat shartnomasi" },
              ],
            },
            {
              title: "2-§. Prokat (583–599)",
              articles: [
                { no: 585, title: "Prokat predmeti" },
                { no: 586, title: "Prokat muddati" },
                { no: 587, title: "Ijara haqi" },
                { no: 588, title: "Ijaraga olingan mol-mulkni ta'mirlash" },
                { no: 589, title: "Prokatda mol-mulkni saqlash" },
                { no: 590, title: "Prokatda mol-mulkni qaytarish" },
                { no: 591, title: "Mol-mulkdan foydalanish to'g'risida ma'lumot berish" },
                { no: 592, title: "Prokatdan voz kechish" },
                { no: 593, title: "Prokat shartnomasini bekor qilish" },
                { no: 594, title: "Yer uchastkalarini ijaraga berish" },
                { no: 595, title: "Yer uchastkalarini ijaraga berishning xususiyatlari" },
                { no: 596, title: "Tabiiy resurslarni ijaraga berishning xususiyatlari" },
                { no: 597, title: "Moliyaviy ijara (lizing)" },
                { no: 598, title: "Moliyaviy ijara (lizing) shartnomasi" },
                { no: 599, title: "Moliyaviy ijara (lizing) qoidalarini qo'llash" },
              ],
            },
          ],
        },

        // --------------------------------------------------
        // 35–37 BOB (600–702)
        // --------------------------------------------------
        {
          title: "35-BOB. UY-JOY IJARASI (600–621)",
          articles: [
            { no: 600, title: "Uy-joy ijarasi shartnomasiga nisbatan qoidalar" },
            { no: 601, title: "Uy-joy ijarasi shartnomasi" },
            { no: 602, title: "Uy-joy ijarasi shartnomasining ob'ekti" },
            { no: 603, title: "Uy-joy ijarasi muddati" },
            { no: 604, title: "Uy-joy ijarasi haqi" },
            { no: 605, title: "Ijaraga oluvchi oila a'zolarining huquqlari" },
            { no: 606, title: "Uy-joy ijarasi shartnomasini o'zgartirish" },
            { no: 607, title: "Ijaraga oluvchining ko'chib ketishi" },
            { no: 608, title: "Uy-joyni ijaraga olish shartnomasiga ijaraga oluvchining yangi oila a'zolarini kiritish" },
            { no: 609, title: "Qisqa muddatli ijara" },
            { no: 610, title: "Uy-joyni ikkilamchi ijaraga berish" },
            { no: 611, title: "Ijaraga berishni bekor qilish" },
            { no: 612, title: "Ijaraga oluvchi tomonidan shartnomasini bekor qilish" },
            { no: 613, title: "Ijaraga beruvchi tomonidan shartnomasini bekor qilish" },
            { no: 614, title: "Ijaraga berishni bekor qilishning oqibatlari" },
            { no: 615, title: "Bepul foydalanish shartnomasi" },
            { no: 616, title: "Mol-mulkni bepul foydalanishga beruvchining majburiyatlari" },
            { no: 617, title: "Mol-mulkni bepul foydalanishga berish taqiqlangan hollar" },
            { no: 618, title: "Bepul foydalanishda mol-mulkni saqlash" },
            { no: 619, title: "Bepul foydalanishda mol-mulkdan foydalanish uchun xarajatlar" },
            { no: 620, title: "Bepul foydalanishda mol-mulkni yaxshilash" },
            { no: 621, title: "Bepul foydalanish shartnomasini bekor qilish" },
          ],
        },
        {
          title: "36-BOB. BEPUL FOYDALANISH (SSUDA) (622–640)",
          articles: [
            { no: 622, title: "Ssuda beruvchining javobgarligi" },
            { no: 623, title: "Ssuda oluvchining javobgarligi" },
            { no: 624, title: "Uchinchi shaxslarga zarar yetkazganlik uchun javobgarlik" },
            { no: 625, title: "Muddatidan oldin bekor qilish" },
            { no: 626, title: "Ssuda beruvchi tomonidan shartnomasini muddatidan oldin bekor qilish" },
            { no: 627, title: "Ssuda oluvchi tomonidan shartnomasini muddatidan oldin bekor qilish" },
            { no: 628, title: "Bepul foydalanish shartnomasini o'zgartirish" },
            { no: 629, title: "Ssuda beruvchi o'lganda yoki qayta tashkil etilganda shartnoma" },
            { no: 630, title: "Pudrat shartnomasi" },
            { no: 631, title: "Pudrat shartnomasi bo'yicha ishlarni bajarish" },
            { no: 632, title: "Pudratchining umumiy majburiyatlari" },
            { no: 633, title: "Ishni uchinchi shaxslarga topshirish" },
            { no: 634, title: "Buyurtmachining pudratchiga ko'rsatma berish huquqi" },
            { no: 635, title: "Buyurtmachi tomonidan material va uskunalar" },
            { no: 636, title: "Ishni bajarish uchun zarur ashyolarni saqlash" },
            { no: 637, title: "Pul mablag'larini saqlash va sarflash" },
            { no: 638, title: "Ish haqi" },
            { no: 639, title: "Ish natijasini topshirish va qabul qilish" },
            { no: 640, title: "Kamchiliklar aniqlangan taqdirda buyurtmachining huquqlari" },
          ],
        },
        {
          title: "37-BOB. PUDRAT (641–702)",
          subchapters: [
            {
              title: "1-§. Umumiy qoidalar (641–668)",
              articles: [
                { no: 641, title: "Ish bajarilganiga kafolat" },
                { no: 642, title: "Kafolat muddati" },
                { no: 643, title: "Kamchiliklar to'g'risida xabardor qilish muddati" },
                { no: 644, title: "Kamchiliklarni bartaraf etish" },
                { no: 645, title: "Pudratchining javobgarligi" },
                { no: 646, title: "Pudrat shartnomasini bekor qilish" },
                { no: 647, title: "Buyurtmachi tomonidan shartnomasini muddatidan oldin bekor qilish" },
                { no: 648, title: "Pudrat shartnomasini bekor qilishning oqibatlari" },
                { no: 649, title: "Ish bajarilmasa pudratchining molmulkini saqlab qolish huquqi" },
                { no: 650, title: "Maishiy pudrat shartnomasi" },
                { no: 651, title: "Iste'molchilarni himoya qilish to'g'risidagi qonunchilikni qo'llash" },
                { no: 652, title: "Maishiy pudratchiga ma'lumot berish majburiyati" },
                { no: 653, title: "Ish bajarilishi uchun zarur material" },
                { no: 654, title: "Ish narxi" },
                { no: 655, title: "Ish narxi to'g'risida smeta" },
                { no: 656, title: "Maishiy pudrat shartnomasi bo'yicha ish narxi to'g'risida xabar berish" },
                { no: 657, title: "Ish natijalari uchun to'lash" },
                { no: 658, title: "Ish bajarilganiga kafolat" },
                { no: 659, title: "Ish natijasi kamchiliklarining oqibatlari" },
                { no: 660, title: "Pudratchining javobgarligi" },
                { no: 661, title: "Ish bajarilishi mumkin bo'lmay qolganida buyurtmachining huquqlari" },
                { no: 662, title: "Ish buyurtmachiga topshirilganda tekshirish" },
                { no: 663, title: "Buyurtmachining buyurtmani qabul qilmasdan qochishi oqibatlari" },
                { no: 664, title: "Maishiy pudrat shartnomasiga nisbatan qoidalarni qo'llash" },
                { no: 665, title: "Maishiy pudrat shartnomasi bo'yicha ish tegishli darajada yoki umuman bajarilmagan taqdirda buyurtmachining huquqlari" },
                { no: 666, title: "Qurilish pudratiga nisbatan umumiy qoidalar" },
                { no: 667, title: "Qurilish pudrati shartnomasi" },
                { no: 668, title: "Pudratchiga yer uchastka va boshqa tayanch asos berish" },
              ],
            },
            {
              title: "2-§. Qurilish pudrati (669–694)",
              articles: [
                { no: 669, title: "Qurilish uchun kerakli hujjatlarni taqdim etish" },
                { no: 670, title: "Texnik hujjatlarga o'zgartirish kiritish" },
                { no: 671, title: "Qurilish pudrati shartnomasi bo'yicha ish narxi" },
                { no: 672, title: "Sug'urta" },
                { no: 673, title: "Qurilishni moliyalashtirish tartibi" },
                { no: 674, title: "Buyurtmachining arxitektura nazorati" },
                { no: 675, title: "Pudratchining arxitektura nazorati" },
                { no: 676, title: "Buyurtmachining qurilish pudrati shartnomasi bo'yicha ishlarning bajarilishini tekshirishi va nazorat qilishi" },
                { no: 677, title: "Qurilish pudrati shartnomasidagi taraflarning hamkorlik qilishi" },
                { no: 678, title: "Pudratchining atrof muhitni muhofaza qilish va qurilish ishlarini xavfsiz olib borish majburiyatlari" },
                { no: 679, title: "Qurilish konservatsiya qilinganda buyurtmachining majburiyatlari" },
                { no: 680, title: "Ishlarni topshirish va qabul qilib olish" },
                { no: 681, title: "Ishning sifati uchun pudratchining javobgarligi" },
                { no: 682, title: "Qurilish pudrati shartnomasida sifat kafolatlari" },
                { no: 683, title: "Kamchiliklarni buyurtmachi hisobidan bartaraf qilish" },
                { no: 684, title: "Loyihalash va qidirish ishlari bo'yicha pudrat shartnomasi" },
                { no: 685, title: "Buyurtmachi tomonidan boshlang'ich ma'lumotlar taqdim etish" },
                { no: 686, title: "Loyihalash va qidirish ishlari bo'yicha pudratchining majburiyatlari" },
                { no: 687, title: "Loyihalash va qidirish ishlari bo'yicha buyurtmachining majburiyatlari" },
                { no: 688, title: "Loyihalash va qidirish ishlaridagi kamchiliklar uchun javobgarlik" },
                { no: 689, title: "Davlat ehtiyojlari uchun pudrat ishlari" },
                { no: 690, title: "Davlat ehtiyojlari uchun pudrat ishlari bo'yicha kontraktni tuzish asoslari" },
                { no: 691, title: "Davlat kontrakt bo'yicha pul to'lash" },
                { no: 692, title: "Kontraktga nisbatan pudrat qoidalarini qo'llash" },
                { no: 693, title: "Haq evaziga xizmat ko'rsatish shartnomasi" },
                { no: 694, title: "Xizmatlar ko'rsatish shartnomasi bo'yicha ijrochi majburiyatlari" },
              ],
            },
            {
              title: "3-§. Haq evaziga xizmat ko'rsatish (695–702)",
              articles: [
                { no: 695, title: "Buyurtmachining majburiyatlari" },
                { no: 696, title: "Haq miqdori" },
                { no: 697, title: "Shartnomani bekor qilish" },
                { no: 698, title: "Haq evaziga xizmat ko'rsatishda pudrat qoidalarini qo'llash" },
                { no: 699, title: "Pudrat va xizmat ko'rsatish qoidalarini qo'llamaslik" },
                { no: 700, title: "Tibbiy xizmat ko'rsatish" },
                { no: 701, title: "Huquqiy va auditorlik xizmatlari" },
                { no: 702, title: "Boshqa xizmat turlari" },
              ],
            },
          ],
        },

        // --------------------------------------------------
        // 38–44 BOB (703–789)
        // --------------------------------------------------
        {
          title: "38-BOB. TASHISH (703–721)",
          articles: [
            { no: 703, title: "Tashish shartnomasi" },
            { no: 704, title: "Yo'lovchilar va bagaj tashish shartnomasi" },
            { no: 705, title: "Yuk tashish shartnomasi" },
            { no: 706, title: "Yuk tashish shartnomasini tuzish tartibi" },
            { no: 707, title: "Yuk jo'natuvchining yukni taqdim etish majburiyati" },
            { no: 708, title: "Tashuvchining yuk topshirishdan bosh tortish huquqi" },
            { no: 709, title: "Yuk jo'natuvchining yuklarni tayyorlash majburiyati" },
            { no: 710, title: "Yuk yukxati" },
            { no: 711, title: "Tashish muddati" },
            { no: 712, title: "Tashuvchining javobgarligi" },
            { no: 713, title: "Bir yo'nalishda har xil transportda tashish" },
            { no: 714, title: "Yo'lovchi tashish shartnomasini bekor qilish" },
            { no: 715, title: "Yo'lovchi yoki bagaj uchun javobgarlik" },
            { no: 716, title: "Tashuvchining yuk saqlanishi uchun javobgarligi" },
            { no: 717, title: "Yetkazib berilgan yuk uchun javobgarlik" },
            { no: 718, title: "Tashish chiqimlarini to'lash" },
            { no: 719, title: "Talab qoʼyish muddatlari" },
            { no: 720, title: "Tashish haqidagi qoidalar" },
            { no: 721, title: "Tashish haqidagi qoidalarni qo'llash" },
          ],
        },
        {
          title: "39-BOB. TRANSPORT EKSPEDITSIYASI (722–731)",
          articles: [
            { no: 722, title: "Transport ekspeditsiyasi shartnomasi" },
            { no: 723, title: "Ekspeditorning majburiyatlari" },
            { no: 724, title: "Ekspeditorning vakolatlari" },
            { no: 725, title: "Ekspeditor tomonidan vazifalari bajarilishini uchinchi shaxsga topshirish" },
            { no: 726, title: "Ekspeditorning javobgarligi" },
            { no: 727, title: "Buyurtmachining majburiyatlari" },
            { no: 728, title: "Buyurtmachining javobgarligi" },
            { no: 729, title: "Ekspeditsiya shartnomani bekor qilish" },
            { no: 730, title: "Qarz shartnomasi" },
            { no: 731, title: "Qarz shartnomasi shakli" },
          ],
        },
        {
          title: "40-BOB. QARZ VA KREDIT (732–755)",
          articles: [
            { no: 732, title: "Qarz shartnomasi bo'yicha foizlar" },
            { no: 733, title: "Qarzni qaytarish muddati va tartibi" },
            { no: 734, title: "Qarzni kechiktirib qaytarishning oqibatlari" },
            { no: 735, title: "Qarz to'lanmaganida undirib olish tartibi" },
            { no: 736, title: "Qarz shartnomasi bekor bo'lganda oqibatlar" },
            { no: 737, title: "Qarz shartnomasi bo'yicha boshqacha shartlar" },
            { no: 738, title: "Davlat qarzlari" },
            { no: 739, title: "Maqsadli qarz" },
            { no: 740, title: "Kredit shartnomasi" },
            { no: 741, title: "Kredit shartnomasi shakli" },
            { no: 742, title: "Kreditni berish yoki olishdan bosh tortish" },
            { no: 743, title: "Maqsadli kredit" },
            { no: 744, title: "Tovar va tijorat krediti" },
            { no: 745, title: "Tovar krediti" },
            { no: 746, title: "Tijorat krediti" },
            { no: 747, title: "Faktorinq" },
            { no: 748, title: "Faktorinq shartnomasi" },
            { no: 749, title: "Faktorinqda pul talabi" },
            { no: 750, title: "Faktorinq pul mablag'lari olishga huquqi" },
            { no: 751, title: "Pul talabini faktorinqqa topshirish to'g'risida qarzdorni xabardor qilish" },
            { no: 752, title: "Qarzdorning moliyaviy agentga toʼlovi" },
            { no: 753, title: "Moliyaviy agent talablarini bajarmaslikning oqibatlari" },
            { no: 754, title: "Faktorinqda garov talablari" },
            { no: 755, title: "Faktorinqda keyingi topshiriq" },
          ],
        },
        {
          title: "41-BOB. BANK OMONATI (756–771)",
          articles: [
            { no: 756, title: "Bank omonati shartnomasi" },
            { no: 757, title: "Bank omonati shakli" },
            { no: 758, title: "Bank omonati turları" },
            { no: 759, title: "Bank omonati bo'yicha foizlar" },
            { no: 760, title: "Omonatni talab qilib olish huquqi" },
            { no: 761, title: "Omonat ma'lumotlari" },
            { no: 762, title: "Uchinchi shaxs omonatlari" },
            { no: 763, title: "Yuridik shaxslar omonatlari" },
            { no: 764, title: "Bank hisobvarag'i shartnomasi" },
            { no: 765, title: "Bank hisobvarag'i shartnomasi bo'yicha to'lovlar" },
            { no: 766, title: "Bank hisobvarag'i bo'yicha to'lovlar muddati" },
            { no: 767, title: "Bank hisobvarag'i bo'yicha to'lovlarni amalga oshirish tartibi" },
            { no: 768, title: "Bank tomonidan hisobvaraqdagi mablag'larni ro'yxatdan o'chirish" },
            { no: 769, title: "Bank hisobvarag'iga to'lanayotgan foizlar" },
            { no: 770, title: "Bank hisobvarag'i bo'yicha sirni saqlash" },
            { no: 771, title: "Bank hisobvarag'i shartnomasini bekor qilish" },
          ],
        },
        {
          title: "42-BOB. BANK HISOB-KITOBLARI (772–789)",
          articles: [
            { no: 772, title: "Hisob-kitob shartnomasi" },
            { no: 773, title: "To'lov topshiriqnomalari" },
            { no: 774, title: "To'lov topshiriqnomasini bajarish" },
            { no: 775, title: "To'lov topshiriqnomasi bajarilishini tekshirish" },
            { no: 776, title: "Akkreditiv" },
            { no: 777, title: "Akkreditivni ochish" },
            { no: 778, title: "Akkreditiv to'lashi" },
            { no: 779, title: "Akkreditivni tasdiqlash" },
            { no: 780, title: "Akkreditivni bekor qilish" },
            { no: 781, title: "Akkreditivda mablag'larni qaytarish" },
            { no: 782, title: "Akkreditiv shartlariga rioya qilinmaganlik uchun javobgarlik" },
            { no: 783, title: "Inkasso bo'yicha hisob-kitoblar" },
            { no: 784, title: "Inkasso topshirig'ini bajarish" },
            { no: 785, title: "To'lovdan yoki akseptdan bosh tortish" },
            { no: 786, title: "Inkasso topshirig'ini bajarishda xabardor qilish" },
            { no: 787, title: "Chek" },
            { no: 788, title: "Chek to'lash" },
            { no: 789, title: "Chek bo'yicha mablag'larni qaytarish" },
          ],
        },

        // --------------------------------------------------
        // 45–49 BOB (790–861)
        // --------------------------------------------------
        {
          title: "43-BOB. DALOLAT NOMASI VA CHEK (790–806)",
          articles: [
            { no: 790, title: "Dalolat nomasi" },
            { no: 791, title: "Veksel" },
            { no: 792, title: "Veksel majburiyatlari" },
            { no: 793, title: "Chek to'lovchi javobgarligi" },
            { no: 794, title: "Cheklarni qo'llash tartibi" },
            { no: 795, title: "Topshiriq shartnomasi" },
            { no: 796, title: "Vakilning majburiyatlari" },
            { no: 797, title: "Topshiriq beruvchining majburiyatlari" },
            { no: 798, title: "Vakilga haq to'lash" },
            { no: 799, title: "Topshiriq berishni o'ziga olgan vakilning javobgarligi" },
            { no: 800, title: "Topshiriq shartnomasi bo'yicha vakolatlarni boshqa shaxsga berish" },
            { no: 801, title: "Topshiriq shartnomasini bekor qilish" },
            { no: 802, title: "Topshiriq shartnomasini bekor qilishning oqibatlari" },
            { no: 803, title: "Alohida huquqlarga ega bo'lgan vakil" },
            { no: 804, title: "Vakil tomonidan xarajatlarni qoplash" },
            { no: 805, title: "Vakilning o'limidan keyin huquqiy vorislik" },
            { no: 806, title: "Topshiriq shartnomasining bekor bo'lishi" },
          ],
        },
        {
          title: "44-BOB. KOMISSIYA SHARTNOMASI (807–818)",
          articles: [
            { no: 807, title: "Komissiya shartnomasi" },
            { no: 808, title: "Vositachi shartnomasi tuzish" },
            { no: 809, title: "Vositachining majburiyatlari" },
            { no: 810, title: "Vositachiga haq to'lash" },
            { no: 811, title: "Vositachining ishni rad etishi" },
            { no: 812, title: "Komissiya shartnomasi bo'yicha topilgan mol-mulk" },
            { no: 813, title: "Komissiya shartnomasi bekor qilinganida mol-mulk" },
            { no: 814, title: "Komissiya shartnomasini bekor qilish" },
            { no: 815, title: "Topshiriq beruvchi tomonidan shartnomasini bekor qilish" },
            { no: 816, title: "Vositachi tomonidan shartnomasini bekor qilish" },
            { no: 817, title: "Ishonchli boshqarish shartnomasi" },
            { no: 818, title: "Topshiriq shartnomasi bo'yicha haq to'lash" },
          ],
        },
        {
          title: "45-BOB. ISHONCHLI BOSHQARISH (819–837)",
          articles: [
            { no: 819, title: "Ishonchli boshqarish asoslari" },
            { no: 820, title: "Ishonchli boshqarish ob'ektlari" },
            { no: 821, title: "Ishonchli boshqaruvchining majburiyatlari" },
            { no: 822, title: "Ishonchli boshqaruvchining vakolatlari" },
            { no: 823, title: "Ishonchli boshqaruvchiga haq to'lash" },
            { no: 824, title: "Ishonchli boshqaruvchining javobgarligi" },
            { no: 825, title: "Ishonchli boshqarish shartnomasini bekor qilish" },
            { no: 826, title: "Oddiy shirkat shartnomasi" },
            { no: 827, title: "Oddiy shirkat shartnomasi bo'yicha hissa" },
            { no: 828, title: "Hissalarning umumiy mulki" },
            { no: 829, title: "Shirkat ishlarini yuritish" },
            { no: 830, title: "Shirkat nomidan vakillik qilish" },
            { no: 831, title: "Umumiy xarajatlar va zararlar" },
            { no: 832, title: "Shirkat foydasini taqsimlash" },
            { no: 833, title: "Ulushni ajratish huquqi" },
            { no: 834, title: "Shirkat a'zosi javobgarligi" },
            { no: 835, title: "Oddiy shirkat shartnomasini bekor qilish" },
            { no: 836, title: "Shirkat shartnomasini bekor qilishning oqibatlari" },
            { no: 837, title: "Maxfiy shirkat shartnomasi" },
          ],
        },
        {
          title: "46-BOB. KOMPLEKS TADBIRKORLIK LITSENZIYASI (838–853)",
          articles: [
            { no: 838, title: "Kompleks tadbirkorlik litsenziyasi shartnomasi" },
            { no: 839, title: "Litsenziya beruvchining majburiyatlari" },
            { no: 840, title: "Litsenziat majburiyatlari" },
            { no: 841, title: "Sublitsenziya" },
            { no: 842, title: "Litsenziya shartnomasini o'zgartirish" },
            { no: 843, title: "Litsenziya shartnomasini bekor qilish" },
            { no: 844, title: "Shartnomaning bekor bo'lishi" },
            { no: 845, title: "Javobgarlik" },
            { no: 846, title: "Omonat saqlash shartnomasi" },
            { no: 847, title: "Omonat saqlovchining majburiyatlari" },
            { no: 848, title: "Omonat saqlovchiga haq to'lash" },
            { no: 849, title: "Omonat saqlovchining javobgarligi" },
            { no: 850, title: "Mol-mulkni boshqa shaxsga saqlash uchun topshirish" },
            { no: 851, title: "Ashyoni topshirish va qaytarish" },
            { no: 852, title: "Omonat saqlash turları" },
            { no: 853, title: "Maxsus omonat saqlash" },
          ],
        },
        {
          title: "47–49-BOB. OMONAT SAQLASH MAXSUS TURLARI VA SUG'URTA (854–861)",
          articles: [
            { no: 854, title: "Tovar omborida saqlash" },
            { no: 855, title: "Ombor guvohnomasi" },
            { no: 856, title: "Lombarda omonat saqlash" },
            { no: 857, title: "Notarius depozitida saqlash" },
            { no: 858, title: "Qimmatli qog'ozlarni saqlash" },
            { no: 859, title: "Yo'lovchilar bagajini saqlash" },
            { no: 860, title: "Muzokara ishtirokchilarining mol-mulkini saqlash" },
            { no: 861, title: "Mehmonxona (motel)larda saqlash" },
          ],
        },

        // --------------------------------------------------
        // 50–58 BOB (862–1030)
        // --------------------------------------------------
        {
          title: "50-BOB. SUG'URTA (862–928)",
          articles: [
            { no: 862, title: "Sug'urta shartnomasi" },
            { no: 863, title: "Sug'urta shartnomasi tuzish" },
            { no: 864, title: "Sug'urta shartnomasining kuchga kirishi" },
            { no: 865, title: "Sug'urta tayiniga oid talablar" },
            { no: 866, title: "Sug'urta tayini" },
            { no: 867, title: "Sug'urta predmetini almashtirish" },
            { no: 868, title: "Mol-mulk sug'urtasi" },
            { no: 869, title: "Fuqarolik javobgarligi sug'urtasi" },
            { no: 870, title: "Tadbirkorlik xavfi sug'urtasi" },
            { no: 871, title: "Shaxsiy sug'urta" },
            { no: 872, title: "Majburiy sug'urta" },
            { no: 873, title: "Sug'urta summasi" },
            { no: 874, title: "Sug'urta mukofoti" },
            { no: 875, title: "Sug'urta muddati" },
            { no: 876, title: "Sug'urta hodisasi" },
            { no: 877, title: "Sug'urta to'lovi" },
            { no: 878, title: "Qo'shma sug'urta" },
            { no: 879, title: "Qayta sug'urta" },
            { no: 880, title: "Sug'urta holati boshlanganda xabardor qilish" },
            { no: 881, title: "Sug'urta to'lovidan bosh tortish asoslari" },
            { no: 882, title: "Javobgarlikni cheklash" },
            { no: 883, title: "Sug'urta shartnomasini bekor qilish" },
            { no: 884, title: "Sug'urta tovoni miqdori" },
            { no: 885, title: "Sug'urtalovchiga subrogatsiya" },
            { no: 886, title: "Mol-mulk sug'urtasining xususiyatlari" },
            { no: 887, title: "Mulk yo'qolishi yoki shikastlanish shaklida sug'urta holati" },
            { no: 888, title: "Mol-mulk taqdiri" },
            { no: 889, title: "Fuqarolik javobgarligi sug'urtasining xususiyatlari" },
            { no: 890, title: "Majburiy sug'urta xususiyatlari" },
            { no: 891, title: "Hayot va sog'liq sug'urtasi" },
            { no: 892, title: "Shaxsiy sug'urtada sug'urta to'lovi" },
            { no: 893, title: "Shaxsiy sug'urtada sug'urta tayini" },
            { no: 894, title: "Bankda omonat saqlash" },
            { no: 895, title: "Bank omonati turlari" },
            { no: 896, title: "Omonat foizlari" },
            { no: 897, title: "Omonatni qaytarish" },
            { no: 898, title: "Omonat haqida ma'lumot" },
            { no: 899, title: "Omonat daftarchasi va omonat sertifikati" },
            { no: 900, title: "Bepul omonat" },
            { no: 901, title: "Omonatga uchinchi shaxs pul qo'yishi" },
            { no: 902, title: "Yuridik shaxslar omonatlari" },
            { no: 903, title: "Bank hisobvarag'i shartnomasi" },
            { no: 904, title: "Hisobvaraq ochish va boshqarish" },
            { no: 905, title: "Hisobvaraq bo'yicha operatsiyalar" },
            { no: 906, title: "Bank tomonidan to'lovlar" },
            { no: 907, title: "Hisobvaraq bo'yicha foizlar" },
            { no: 908, title: "Bank hisobvarag'i bo'yicha maxfiylik" },
            { no: 909, title: "Bank hisobvarag'ini yopish" },
            { no: 910, title: "Zarar yetkazishdan kelib chiqadigan majburiyatlar" },
            { no: 911, title: "Zarar yetkazganlik uchun javobgarlik asoslari" },
            { no: 912, title: "Nodavlat xavfsizlik" },
            { no: 913, title: "Zarar yetkazgan shaxsning javobgarlikdan ozod bo'lishi" },
          ],
        },
        {
          title: "51–57-BOB. ZARAR YETKAZISHDAN KELIB CHIQADIGAN MAJBURIYATLAR (914–1022)",
          articles: [
            { no: 914, title: "Zarar yetkazishning umumiy qoidalar" },
            { no: 915, title: "Zararga haq to'lash holatlari" },
            { no: 916, title: "Yukori xavfli manba egasining javobgarligi" },
            { no: 917, title: "Davlat organlari faoliyatidan zarar" },
            { no: 918, title: "Noto'g'ri yuridik harakatlar tufayli zarar" },
            { no: 919, title: "Voyaga yetmaganlarning javobgarligi" },
            { no: 920, title: "Muomalaga layoqatsizlarning javobgarligi" },
            { no: 921, title: "Muomala layoqati cheklanganning javobgarligi" },
            { no: 922, title: "Yuridik shaxs xodimlarining harakatlari uchun javobgarlik" },
            { no: 923, title: "Birgalikda zarar yetkazganlik uchun javobgarlik" },
            { no: 924, title: "Regress talablari" },
            { no: 925, title: "Zarar miqdorini aniqlash" },
            { no: 926, title: "Hayotga zarar yetkazish" },
            { no: 927, title: "Sog'liqqa zarar yetkazish" },
            { no: 928, title: "Boquvchisidan mahrum qilingan holda zarar" },
            { no: 929, title: "Zarar to'lovlari" },
            { no: 930, title: "Zarar to'lovlarini o'zgartirish" },
            { no: 931, title: "Hayot va sog'liqqa zarar to'lovlari indeksatsiyasi" },
            { no: 932, title: "Tovar va xizmatlarning kamchiliklari uchun javobgarlik" },
            { no: 933, title: "Tovar kamchiliklari uchun javobgarlik" },
            { no: 934, title: "Ma'lumot kamchiliklari uchun javobgarlik" },
            { no: 935, title: "Zarar yetkazilganida jismoniy shaxslar xuquqlari" },
            { no: 936, title: "Zarar to'lash muddatlari" },
            { no: 937, title: "Ishlab chiqaruvchi javobgarligi" },
            { no: 938, title: "Ma'naviy ziyonni qoplash" },
            { no: 939, title: "Ma'naviy ziyonni baholash" },
            { no: 940, title: "Ma'naviy ziyonni to'lash tartibi" },
            { no: 941, title: "Ommaviy axborot vositalari ma'naviy ziyoni" },
            { no: 942, title: "Asossiz boyib ketish" },
            { no: 943, title: "Asossiz boyib ketish oqibatlari" },
            { no: 944, title: "Asossiz boyib ketish holatlarining o'ziga xosligi" },
            { no: 945, title: "Asossiz boyib ketish va zarar to'lash" },
            { no: 946, title: "Asossiz boyib ketish va huquqni boshqa shaxsga o'tkazish" },
            { no: 985, title: "Ma'naviy zararning qoplanishi" },
            { no: 993, title: "Mulk huquqi va boshqa huquqlarni asossiz olish" },
            { no: 998, title: "Asossiz boyib ketish" },
            { no: 999, title: "Asossiz boyib ketishni qaytarish" },
            { no: 1003, title: "Huquqni asossiz berish" },
            { no: 1009, title: "Olinmagan daromad" },
            { no: 1012, title: "Xarajatlarni qoplash" },
          ],
        },
        {
          title: "58-BOB. ASOSSIZ BOYIB KETISH (1023–1030)",
          articles: [
            { no: 1023, title: "Asossiz boyib ketishga oid talablarning boshqa talablar bilan bog'liqligi" },
            { no: 1024, title: "Asossiz orttirilgan boylikni qaytarish to'g'risidagi talablarning fuqarolik huquqlarini himoya qilish to'g'risidagi boshqa talablar bilan o'zaro bog'lanishi" },
            { no: 1025, title: "Asossiz orttirilgan boylikni asl holida qaytarish" },
            { no: 1026, title: "Asossiz orttirilgan boylikning qiymatini to'lash" },
            { no: 1027, title: "Huquqni boshqa shaxsga asossiz berish oqibatlari" },
            { no: 1028, title: "Jabrlanuvchiga olinmagan daromadlarni to'lash" },
            { no: 1029, title: "Qaytarilishi lozim bo'lgan mol-mulkka qilingan xarajatlarni to'lash" },
            { no: 1030, title: "Qaytarib berilmaydigan asossiz orttirilgan boylik" },
          ],
        },
      ],
    },

    // ========================================================
    // IV BO'LIM — INTELLEKTUAL MULK (59–65 bob, 1031–1111)
    // ========================================================
    {
      title: "IV BO'LIM. INTELLEKTUAL MULK (59–65 bob, 1031–1111)",
      chapters: [
        {
          title: "59-BOB. UMUMIY QOIDALAR (1031–1036)",
          articles: [
            { no: 1031, title: "Intellektual mulk tushunchasi" },
            { no: 1032, title: "Intellektual faoliyat natijalaridan foydalanish" },
            { no: 1033, title: "Intellektual mulk huquqining vujudga kelishi" },
            { no: 1034, title: "Intellektual mulk huquqlarini berish" },
            { no: 1035, title: "Intellektual mulk huquqini boshqa shaxsga o'tkazish" },
            { no: 1036, title: "Intellektual mulk huquqini boshqa shaxsga o'tkazish tartibi" },
          ],
        },
        {
          title: "60-BOB. INTELLEKTUAL FAOLIYAT NATIJALARINI YARATISH VA ULARDAN FOYDALANISH (1037–1050)",
          articles: [
            { no: 1037, title: "Intellektual faoliyat natijalarini yaratish va ulardan foydalanish to'g'risidagi shartnoma" },
            { no: 1038, title: "Shartnoma bo'yicha muallifga to'lov" },
            { no: 1039, title: "Asarni taqdim etish muddati" },
            { no: 1040, title: "Muallifning huquqlari va majburiyatlari" },
            { no: 1041, title: "Asardan foydalanish muddati" },
            { no: 1042, title: "Natijaning o'ziga xosligi" },
            { no: 1043, title: "Shartnomani bekor qilish" },
            { no: 1044, title: "Muallifga mukofot to'lash" },
            { no: 1045, title: "Muallif va tashkilot o'rtasidagi munosabatlar" },
            { no: 1046, title: "Xizmat asarlari" },
            { no: 1047, title: "Muallif huquqlarini himoya qilish" },
            { no: 1048, title: "Mualliflik huquqi" },
            { no: 1049, title: "Mualliflik huquqining vujudga kelishi" },
            { no: 1050, title: "Mualliflik huquqining subyektlari" },
          ],
        },
        {
          title: "61-BOB. MUALLIFLIK HUQUQI (1051–1073)",
          articles: [
            { no: 1051, title: "Mualliflik huquqi ob'ektlari" },
            { no: 1052, title: "Muallifning shaxsiy nomulkiy huquqlari" },
            { no: 1053, title: "Muallifning mulkiy huquqlari" },
            { no: 1054, title: "Asardan foydalanish shartnomasi" },
            { no: 1055, title: "Asardan foydalanish uchun haq" },
            { no: 1056, title: "Mualliflik huquqini buzish uchun javobgarlik" },
            { no: 1057, title: "Asardan foydalanish chegaralari" },
            { no: 1058, title: "Asardan erkin foydalanish holatlari" },
            { no: 1059, title: "Asarlarni muallifning roziligisiz va haq to'lanmagan holda shaxsiy maqsadlarda takrorlash" },
            { no: 1060, title: "Asarlarni omma oldida erkin ijro etish" },
            { no: 1061, title: "Asarlarni erkin ko'chirish va chiqarish" },
            { no: 1062, title: "Asarlarni erkin tarjima qilish" },
            { no: 1063, title: "Mualliflik huquqi muddati" },
            { no: 1064, title: "Mualliflik huquqini meros qilib olish" },
            { no: 1065, title: "Mualliflik huquqini boshqa shaxsga berish" },
            { no: 1066, title: "Jamoa asarlari" },
            { no: 1067, title: "Birgalikda mualliflik" },
            { no: 1068, title: "Tarkibiy (yig'ma) asarlar" },
            { no: 1069, title: "Vaqtli nashrlar asarlari" },
            { no: 1070, title: "Tarjimalar va hosilaviy asarlar" },
            { no: 1071, title: "Turdosh huquqlar" },
            { no: 1072, title: "Ijrochi huquqlari" },
            { no: 1073, title: "Mualliflik munosabatlarini huquqiy jihatdan tartibga solish" },
          ],
        },
        {
          title: "62-BOB. SANOAT MULKIGA BO'LGAN HUQUQ (1082–1095)",
          articles: [
            { no: 1074, title: "Fonogramma ishlab chiqaruvchi huquqlari" },
            { no: 1075, title: "Efir va kabel orqali eshittirish tashkilotlari huquqlari" },
            { no: 1076, title: "Turdosh huquqlarni himoya qilish" },
            { no: 1077, title: "Turdosh huquqlar muddati" },
            { no: 1078, title: "Turdosh huquqlarni boshqa shaxsga berish" },
            { no: 1079, title: "Turdosh huquqlarni buzish uchun javobgarlik" },
            { no: 1080, title: "[O'z kuchini yo'qotgan — OʻRQ-79, 2007]" },
            { no: 1081, title: "[O'z kuchini yo'qotgan — OʻRQ-79, 2007]" },
            { no: 1082, title: "Ixtiro, foydali model, sanoat namunasiga nisbatan qo'yiladigan talablar" },
            { no: 1083, title: "Patent olish huquqi" },
            { no: 1084, title: "Patent egasining huquqlari" },
            { no: 1085, title: "Patent litsenziyasi" },
            { no: 1086, title: "Patentni majburiy litsenziyalash" },
            { no: 1087, title: "Patent egasining huquqlarini himoya qilish" },
            { no: 1088, title: "Patent egasining huquqlari buzilganda javobgarlik" },
            { no: 1089, title: "Xizmat ixtirosi, foydali modeli, sanoat namunasi" },
            { no: 1090, title: "Seleksion yutuqlar" },
            { no: 1091, title: "Seleksion yutuqqa patent olish" },
            { no: 1092, title: "Patent egasining seleksion yutuq huquqlari" },
            { no: 1093, title: "Seleksion yutuqni litsenziyalash" },
            { no: 1094, title: "Seleksion yutuq huquqlarini himoya qilish" },
            { no: 1095, title: "EHM dasturlari va ma'lumotlar bazalari" },
          ],
        },
        {
          title: "63-BOB. EHM DASTURLARI, MA'LUMOTLAR BAZALARI VA INTEGRAL MIKROSXEMALAR TOPOLOGIYALARI (1096–1104)",
          articles: [
            { no: 1096, title: "EHM dasturlari va ma'lumotlar bazalariga bo'lgan huquqlar" },
            { no: 1097, title: "Dastur va ma'lumotlar bazasiga bo'lgan huquqlar muddati" },
            { no: 1098, title: "Dastur va ma'lumotlar bazasidan foydalanish" },
            { no: 1099, title: "Integral mikrosxemalar topologiyalariga bo'lgan huquq" },
            { no: 1100, title: "Integral mikrosxema topologiyasiga bo'lgan huquqlar muddati" },
            { no: 1101, title: "Topologiyadan foydalanish" },
            { no: 1102, title: "Topologiya huquqlarini buzish uchun javobgarlik" },
            { no: 1103, title: "Topologiya muallif huquqlari" },
            { no: 1104, title: "Topologiya huquqlarini boshqa shaxsga berish" },
          ],
        },
        {
          title: "64-BOB. FIRMA NOMLARI, TOVAR VA XIZMAT KO'RSATISH BELGILARI (1105–1111)",
          articles: [
            { no: 1105, title: "Firma nomi" },
            { no: 1106, title: "Tovar belgisiga bo'lgan huquqni boshqa shaxsga berish to'g'risidagi shartnomaning shakli" },
            { no: 1107, title: "Tovar belgisiga bo'lgan huquqni buzganlik uchun javobgarlik" },
            { no: '1107¹', title: "Tovar belgisiga doir mutlaq huquqning tugashi" },
            { no: 1108, title: "Xizmat ko'rsatish belgisi" },
            { no: 1109, title: "Tovar kelib chiqqan joyning nomi" },
            { no: 1110, title: "Tovar kelib chiqqan joyning nomini himoya qilish" },
            { no: 1111, title: "Intellektual mulk huquqlarini buzganlik uchun javobgarlik" },
          ],
        },
      ],
    },

    // ========================================================
    // V BO'LIM — VORISLIK HUQUQI (66–69 bob, 1112–1157)
    // ========================================================
    {
      title: "V BO'LIM. VORISLIK HUQUQI (66–69 bob, 1112–1157)",
      chapters: [
        {
          title: "66-BOB. VORISLIKNING UMUMIY QOIDALARI (1112–1130)",
          articles: [
            { no: 1112, title: "Vorislik tushunchasi" },
            { no: 1113, title: "Merosni qabul qilish" },
            { no: 1114, title: "Merosni ochilish vaqti va joyi" },
            { no: 1115, title: "Merosga kirish huquqi" },
            { no: 1116, title: "Qonuniy vorislar" },
            { no: 1117, title: "Merosxo'r bo'lmagan shaxslar" },
            { no: 1118, title: "Vasiyat bo'yicha meros" },
            { no: 1119, title: "Vasiyatnoma tuzish erkinligi" },
            { no: 1120, title: "Vasiyatnoma shakli" },
            { no: 1121, title: "Vasiyatnomani guvoh ishtirokida tuzish" },
            { no: 1122, title: "Maxfiy vasiyatnoma" },
            { no: 1123, title: "Vasiyatnomani bekor qilish" },
            { no: 1124, title: "Vasiyatnomani ijro etish" },
            { no: 1125, title: "Majburiy ulush" },
            { no: 1126, title: "Qonuniy vorislik tartibi" },
            { no: 1127, title: "Birinchi navbatdagi vorislar" },
            { no: 1128, title: "Ikkinchi navbatdagi vorislar" },
            { no: 1129, title: "Uchinchi navbatdagi vorislar" },
            { no: 1130, title: "To'rtinchi navbatdagi vorislar" },
          ],
        },
        {
          title: "67-BOB. MEROS QABUL QILISH (1131–1143)",
          articles: [
            { no: 1131, title: "Merosni qabul qilish tartibi" },
            { no: 1132, title: "Merosni qabul qilish muddati" },
            { no: 1133, title: "Merosni qabul qilish muddatini tiklash" },
            { no: 1134, title: "Merosdan voz kechish" },
            { no: 1135, title: "Merosdan voz kechish shakli" },
            { no: 1136, title: "Muayyan shaxs foydasiga merosdan voz kechish" },
            { no: 1137, title: "Merosni taqsimlash" },
            { no: 1138, title: "Merosni taqsimlash tartibi" },
            { no: 1139, title: "Meros mol-mulk" },
            { no: 1140, title: "Vorislarning javobgarligi" },
            { no: 1141, title: "Merosda ulushlar" },
            { no: 1142, title: "Merosda imtiyozli huquqlar" },
            { no: 1143, title: "Meros mol-mulkni saqlash" },
          ],
        },
        {
          title: "68-BOB. DAVLATGA O'TUVCHI MEROS (1144–1150)",
          articles: [
            { no: 1144, title: "Meros mol-mulkning davlatga o'tishi" },
            { no: 1145, title: "Davlat mulki sifatida meros" },
            { no: 1146, title: "Vasiyat mazmuni" },
            { no: 1147, title: "Mulk topshirilishi (meros legatlar)" },
            { no: 1148, title: "Meros legatlar tartibi" },
            { no: 1149, title: "Vasiyat belgilash" },
            { no: 1150, title: "Davlat vorisligining xususiyatlari" },
          ],
        },
        {
          title: "69-BOB. ALOHIDA MEROS TURLARI (1151–1157)",
          articles: [
            { no: 1151, title: "Korxonalarni meros qilib olish" },
            { no: 1152, title: "Qishloq xo'jaligi jamoa (fermer) xo'jaligi a'zolari meros" },
            { no: 1153, title: "Cheklangan muomaladagi mol-mulkni meros qilib olish" },
            { no: 1154, title: "Yer uchastkalarini meros qilib olish" },
            { no: 1155, title: "Haq evaziga beriladigan xizmatlar huquqini meros qilib olish" },
            { no: 1156, title: "Intellektual faoliyat natijalari huquqini meros qilib olish" },
            { no: 1157, title: "Bank omonatlarini meros qilib olish" },
          ],
        },
      ],
    },

    // ========================================================
    // VI BO'LIM — XALQARO XUSUSIY HUQUQ NORMALARI (70–71 bob, 1158–1199)
    // ========================================================
    {
      title: "VI BO'LIM. XALQARO XUSUSIY HUQUQ NORMALARINI FUQAROLIK-HUQUQIY MUNOSABATLARGA NISBATAN TATBIQ QILISH (70–71 bob, 1158–1199)",
      chapters: [
        {
          title: "70-BOB. UMUMIY QOIDALAR (1158–1181)",
          articles: [
            { no: 1158, title: "Chet el elementi bilan murakkablashgan fuqarolik-huquqiy munosabatlarga nisbatan qo'llanilishi lozim bo'lgan huquqni belgilash" },
            { no: 1159, title: "Huquqni tanlash" },
            { no: 1160, title: "Davlat immunitetini qo'llash" },
            { no: 1161, title: "Chet el huquqini qo'llash tartibi" },
            { no: 1162, title: "Chet el huquqini sud tomonidan aniqlash" },
            { no: 1163, title: "Fuqaro fuqaroligiga bo'lgan huquq" },
            { no: 1164, title: "Shaxsiy qonun" },
            { no: 1165, title: "Jismoniy shaxsning huquq va muomala layoqati" },
            { no: 1166, title: "Yuridik shaxsning shaxsiy qonuni" },
            { no: 1167, title: "Xorijiy yuridik shaxslarning fuqarolik huquq layoqati" },
            { no: 1168, title: "Moddiy huquqni qo'llash qayta yo'naltiruvchisi" },
            { no: 1169, title: "Shartnomalar bo'yicha huquq" },
            { no: 1170, title: "Taraflarning shartnomada huquqni tanlashi" },
            { no: 1171, title: "Shartnomaga aloqador huquq" },
            { no: 1172, title: "O'zbekiston Respublikasi hududidan tashqarida O'zbekiston Respublikasi fuqarolarining fuqarolik holati hujjatlarini qayd etish" },
            { no: 1173, title: "Fuqarolik holati hujjatlarini tasdiqlash uchun xorijiy davlat organlari tomonidan berilgan hujjatlarni tan olish" },
            { no: 1174, title: "Ism huquqi" },
            { no: 1175, title: "Fuqarolik holati dalolatnomalarini tan olish" },
            { no: 1176, title: "Opeka va vasiylik" },
            { no: 1177, title: "Xorij mulk huquqining qo'llanilishi" },
            { no: 1178, title: "Ko'chmas mulk" },
            { no: 1179, title: "Fuqaroni bedarak yo'qolgan deb topish" },
            { no: 1180, title: "Fuqaroni vafot etgan deb e'lon qilish" },
            { no: 1181, title: "Zarar yetkazish bo'yicha majburiyatlar" },
          ],
        },
        {
          title: "71-BOB. XALQARO XUSUSIY HUQUQ MAXSUS QOIDALARI (1182–1199)",
          articles: [
            { no: 1182, title: "Asossiz boyib ketish bo'yicha majburiyatlar" },
            { no: 1183, title: "Vorislik huquqi" },
            { no: 1184, title: "Xalqaro shartnomalar bo'yicha vorislik" },
            { no: 1185, title: "Intellektual mulk bo'yicha huquq" },
            { no: 1186, title: "Chet el huquqi normalarini qo'llash chegaralari" },
            { no: 1187, title: "O'zaro aloqa tamoyili" },
            { no: 1188, title: "Ommaviy tartib" },
            { no: 1189, title: "Xalqaro shartnoma normalarining ustunligi" },
            { no: 1190, title: "Xalqaro xususiy huquq to'g'risidagi qonunchilik" },
            { no: 1191, title: "Hakamlik sudi shartnomasi" },
            { no: 1192, title: "Hakamlik sudi bitimi" },
            { no: 1193, title: "Chet el hakamlik sudi qarorlarini tan olish" },
            { no: 1194, title: "Chet el hakamlik sudi qarorlarini ijro etish" },
            { no: 1195, title: "Chet el sud qarorlarini tan olish va ijro etish" },
            { no: 1196, title: "Xalqaro shartnomalar bo'yicha huquqiy yordam" },
            { no: 1197, title: "Suddagi muassasalar va chet el huquqiy normalar" },
            { no: 1198, title: "Notarial harakatlar va chet el huquq" },
            { no: 1199, title: "Xalqaro xususiy huquq bo'yicha xulosa qoidalar" },
          ],
        },
      ],
    },
  ],
};

module.exports = CIVIL_CODE_PART2_TOC;
